#!/usr/bin/env python3
"""Generate adaptive Screen 3 flow data for index.html integration."""

import json
import re
from pathlib import Path

from s3_conversational_templates import FLOWS
from s3_curated_data import OVERRIDES, SUBTYPE_CTX

ROOT = Path(__file__).resolve().parents[1]

S2 = {
    "service": ["IT & TECH","CONSULTING","LEGAL","ACCOUNTING","MARKETING","HEALTHCARE","STAFFING","CLEANING","SECURITY","HOSPITALITY","FOOD SERVICE","CREATIVE"],
    "manufacturing": ["FOOD & BEV","ELECTRONICS","TEXTILES","CHEMICALS","METAL & STEEL","AUTOMOTIVE","FURNITURE","MEDICAL","CONSTRUCTION","PLASTICS","PRINT & PAPER","AGRI-PROC"],
    "agriculture": ["CROP FARMING","LIVESTOCK","DAIRY","POULTRY","AQUACULTURE","HORTICULTURE","ORGANIC","PROCESSING","PLANTATION","SEED SUPPLY","IRRIGATION","EXPORT/TRADE"],
    "logistics": ["ROAD/TRUCKING","AIR FREIGHT","SEA/OCEAN","RAIL","WAREHOUSING","LAST MILE","COLD CHAIN","CUSTOMS","SUPPLY CHAIN","MOVING","E-COMM FULFIL","FREIGHT FWDG"],
    "finance": ["BANKING","INSURANCE","INVESTMENT","ACCOUNTING","FINTECH","LENDING","WEALTH MGMT","PAYMENTS","CRYPTO","RISK","TRADING","MICROFINANCE"],
    "construction": ["RESIDENTIAL","COMMERCIAL","INFRASTRUCTURE","ELECTRICAL","PLUMBING","INTERIOR","RENOVATION","DEMOLITION","REAL ESTATE","CIVIL ENG","ENVIRONMENTAL","FUEL/ENERGY"],
    "retail": ["APPAREL","ELECTRONICS","GROCERY","HARDWARE","PHARMACY","FURNITURE","JEWELRY","SPORTING","E-COMMERCE","AUTO PARTS","BOOKS/STAT","HOME DECOR"],
    "education": ["K-12","HIGHER ED","VOCATIONAL","ED-TECH","CORP TRAINING","TUTORING","LANGUAGE","TEST PREP","ARTS & MUSIC","SPORTS","EARLY CHILD","SPECIAL ED"],
    "entertainment": ["MUSIC","FILM & VIDEO","GAMING","LIVE EVENTS","STREAMING","SOCIAL MEDIA","PUBLISHING","PHOTOGRAPHY","ANIMATION","THEATRE","SPORTS MEDIA","ADVERTISING"],
}

CAT_LABEL = {
    "service": "service business",
    "manufacturing": "manufacturing operation",
    "agriculture": "agriculture operation",
    "logistics": "logistics operation",
    "finance": "financial services firm",
    "construction": "construction business",
    "retail": "retail operation",
    "education": "education provider",
    "entertainment": "entertainment business",
}

def slug(name: str) -> str:
    s = name.lower().replace("/", "-").replace("&", "").strip()
    s = re.sub(r"[^a-z0-9\s-]", "", s)
    s = re.sub(r"\s+", "-", s)
    return re.sub(r"-+", "-", s).strip("-")

def default_ctx(category: str, subtype: str) -> dict:
    st = subtype.lower()
    return {
        "subtype": subtype,
        "category": CAT_LABEL[category],
        "client": "customer" if category in ("retail", "logistics") else "client",
        "unit": "this kind of work",
        "work": "job",
        "deliver": "wrap it up",
    }

def merge_ctx(category: str, subtype: str) -> dict:
    base = default_ctx(category, subtype)
    base.update(SUBTYPE_CTX.get((category, subtype), {}))
    base["title"] = f"YOUR {subtype} OPERATION, STAGE BY STAGE"
    return base
def fill(template: str, ctx: dict) -> str:
    out = template
    for k, v in ctx.items():
        out = out.replace("{" + k + "}", v)
    return out

def build_flow(category: str, subtype: str) -> dict:
    ctx = merge_ctx(category, subtype)
    base = FLOWS[category]
    stages = []
    for i, st in enumerate(base["stages"]):
        stage = dict(st)
        ov = OVERRIDES.get((category, subtype), {}).get(i, {})
        stage.update(ov)
        stage = {
            "name": stage["name"],
            "icon": "S3_ICON." + stage["icon"],
            "q": fill(stage["q"], ctx),
            "options": [{"text": fill(stage["opts"][j], ctx), "state": stage["states"][j]} for j in range(3)],
            "diag": {k: fill(v, ctx) for k, v in stage["diag"].items()},
            "fix": fill(stage["fix"], ctx),
        }
        stages.append(stage)
    return {"title": ctx["title"], "stages": stages}

# Build lookup table for all combos
lookup = {}
for cat, subtypes in S2.items():
    for st in subtypes:
        key = cat + "|" + slug(st)
        lookup[key] = build_flow(cat, st)

# Normalize icon keys before serializing
for flow in lookup.values():
    for st in flow["stages"]:
        st["icon"] = st["icon"].replace("S3_ICON.", "")

adaptive_js = (
    "/* S3_ADAPTIVE_BEGIN — generated by tools/generate_s3_adaptive.py */\n"
    + "var S3_FLOW_LOOKUP = "
    + json.dumps(lookup, ensure_ascii=False, separators=(",", ":"))
    + ";\n"
    + r'''
function s3Slug(name) {
  return name.toLowerCase().replace(/\//g, '-').replace(/&/g, '').replace(/\s+/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
}

function resolveS3Flow(categoryKey, subtypeName) {
  if (!categoryKey || !subtypeName || typeof S3_FLOW_LOOKUP === 'undefined') return S3_FLOW_DEFAULT;
  var key = categoryKey + '|' + s3Slug(subtypeName);
  var raw = S3_FLOW_LOOKUP[key];
  if (!raw) return S3_FLOW_DEFAULT;
  var stages = raw.stages.map(function(st) {
    return {
      name: st.name,
      icon: S3_ICON[st.icon] || S3_ICON.lead,
      q: st.q,
      options: st.options.slice(),
      diag: { shaky: st.diag.shaky, missing: st.diag.missing },
      fix: st.fix
    };
  });
  return { title: raw.title, stages: stages };
}
/* S3_ADAPTIVE_END */
'''
)

out_path = ROOT / "tools" / "s3-flow-data.js"
out_path.write_text(adaptive_js, encoding="utf-8")
print(f"Wrote {out_path} ({len(lookup)} flows)")

index_path = ROOT / "index.html"
html = index_path.read_text(encoding="utf-8")
begin = "/* S3_ADAPTIVE_BEGIN"
end = "/* S3_ADAPTIVE_END */"
if begin in html and end in html:
    start = html.index(begin)
    finish = html.index(end) + len(end)
    html = html[:start] + adaptive_js.strip() + html[finish:]
else:
    html = html.replace(
        '<script src="tools/s3-flow-data.js"></script>\n',
        "<script>\n" + adaptive_js + "</script>\n",
    )
index_path.write_text(html, encoding="utf-8")
print(f"Inlined adaptive flow data into {index_path}")
