"""Hand-curated subtype context and stage overrides for Screen 3 flows."""

# client / unit / work / deliver placeholders per subtype
SUBTYPE_CTX = {
    # ── SERVICE ──
    ("service", "IT & TECH"): {"client": "prospect", "unit": "a software project", "work": "project", "deliver": "ship the build"},
    ("service", "CONSULTING"): {"client": "prospect", "unit": "an advisory project", "work": "engagement", "deliver": "deliver recommendations"},
    ("service", "LEGAL"): {"client": "potential client", "unit": "a legal matter", "work": "case", "deliver": "close the matter"},
    ("service", "ACCOUNTING"): {"client": "client", "unit": "their books", "work": "engagement", "deliver": "close the books"},
    ("service", "MARKETING"): {"client": "brand client", "unit": "a campaign", "work": "campaign", "deliver": "launch the campaign"},
    ("service", "HEALTHCARE"): {"client": "patient", "unit": "an appointment or care plan", "work": "care plan", "deliver": "deliver care"},
    ("service", "STAFFING"): {"client": "hiring manager", "unit": "an open role", "work": "placement", "deliver": "fill the role"},
    ("service", "CLEANING"): {"client": "client", "unit": "a cleaning contract", "work": "route", "deliver": "complete the clean"},
    ("service", "SECURITY"): {"client": "client", "unit": "a site or patrol contract", "work": "shift", "deliver": "secure the site"},
    ("service", "HOSPITALITY"): {"client": "guest", "unit": "a booking", "work": "stay", "deliver": "deliver the experience"},
    ("service", "FOOD SERVICE"): {"client": "customer", "unit": "an event or service", "work": "service", "deliver": "serve the event"},
    ("service", "CREATIVE"): {"client": "client", "unit": "a creative brief", "work": "deliverable", "deliver": "deliver the assets"},
    # ── MANUFACTURING ──
    ("manufacturing", "FOOD & BEV"): {"client": "buyer", "unit": "a production batch", "work": "batch", "deliver": "release batch"},
    ("manufacturing", "ELECTRONICS"): {"client": "buyer", "unit": "a production run", "work": "run", "deliver": "ship units"},
    ("manufacturing", "TEXTILES"): {"client": "buyer", "unit": "a fabric production lot", "work": "lot", "deliver": "ship the roll"},
    ("manufacturing", "CHEMICALS"): {"client": "buyer", "unit": "a chemical batch", "work": "batch", "deliver": "release to spec"},
    ("manufacturing", "METAL & STEEL"): {"client": "buyer", "unit": "a fabrication order", "work": "order", "deliver": "deliver fabricated parts"},
    ("manufacturing", "AUTOMOTIVE"): {"client": "OEM", "unit": "a parts production run", "work": "run", "deliver": "ship to line"},
    ("manufacturing", "FURNITURE"): {"client": "buyer", "unit": "a furniture production order", "work": "order", "deliver": "ship finished goods"},
    ("manufacturing", "MEDICAL"): {"client": "buyer", "unit": "a regulated device batch", "work": "batch", "deliver": "release with documentation"},
    ("manufacturing", "CONSTRUCTION"): {"client": "contractor", "unit": "a materials production order", "work": "order", "deliver": "deliver to site"},
    ("manufacturing", "PLASTICS"): {"client": "buyer", "unit": "an injection molding run", "work": "run", "deliver": "ship molded parts"},
    ("manufacturing", "PRINT & PAPER"): {"client": "buyer", "unit": "a print production job", "work": "job", "deliver": "deliver the print run"},
    ("manufacturing", "AGRI-PROC"): {"client": "buyer", "unit": "a processing batch", "work": "batch", "deliver": "release packaged goods"},
    # ── AGRICULTURE ──
    ("agriculture", "CROP FARMING"): {"client": "buyer", "unit": "a harvest lot", "work": "season", "deliver": "move the crop"},
    ("agriculture", "LIVESTOCK"): {"client": "buyer", "unit": "a livestock lot", "work": "herd cycle", "deliver": "deliver animals or meat"},
    ("agriculture", "DAIRY"): {"client": "buyer", "unit": "a daily milk collection", "work": "collection", "deliver": "deliver milk"},
    ("agriculture", "POULTRY"): {"client": "buyer", "unit": "a flock batch", "work": "flock cycle", "deliver": "process and ship"},
    ("agriculture", "AQUACULTURE"): {"client": "buyer", "unit": "a pond or tank harvest", "work": "harvest", "deliver": "ship fresh stock"},
    ("agriculture", "HORTICULTURE"): {"client": "buyer", "unit": "a greenhouse harvest", "work": "harvest", "deliver": "deliver produce"},
    ("agriculture", "ORGANIC"): {"client": "buyer", "unit": "a certified organic lot", "work": "season", "deliver": "deliver certified produce"},
    ("agriculture", "PROCESSING"): {"client": "buyer", "unit": "a value-add processing run", "work": "run", "deliver": "ship packaged goods"},
    ("agriculture", "PLANTATION"): {"client": "buyer", "unit": "a plantation harvest", "work": "harvest", "deliver": "process and export"},
    ("agriculture", "SEED SUPPLY"): {"client": "farmer", "unit": "a seed or input order", "work": "order", "deliver": "deliver inputs on time"},
    ("agriculture", "IRRIGATION"): {"client": "farmer", "unit": "an irrigation install or service", "work": "project", "deliver": "commission the system"},
    ("agriculture", "EXPORT/TRADE"): {"client": "importer", "unit": "an export shipment", "work": "shipment", "deliver": "clear customs and deliver"},
    # ── LOGISTICS ──
    ("logistics", "ROAD/TRUCKING"): {"client": "shipper", "unit": "a full truckload", "work": "load", "deliver": "deliver on time"},
    ("logistics", "AIR FREIGHT"): {"client": "shipper", "unit": "an air cargo booking", "work": "consignment", "deliver": "deliver to consignee"},
    ("logistics", "SEA/OCEAN"): {"client": "shipper", "unit": "a container booking", "work": "shipment", "deliver": "release at port"},
    ("logistics", "RAIL"): {"client": "shipper", "unit": "a rail car load", "work": "consignment", "deliver": "deliver at terminal"},
    ("logistics", "WAREHOUSING"): {"client": "client", "unit": "an inbound inventory batch", "work": "fulfillment wave", "deliver": "ship orders"},
    ("logistics", "LAST MILE"): {"client": "customer", "unit": "a same-day delivery", "work": "route", "deliver": "complete delivery"},
    ("logistics", "COLD CHAIN"): {"client": "shipper", "unit": "a temperature-sensitive shipment", "work": "load", "deliver": "deliver in-spec"},
    ("logistics", "CUSTOMS"): {"client": "importer", "unit": "a customs clearance file", "work": "clearance", "deliver": "release shipment"},
    ("logistics", "SUPPLY CHAIN"): {"client": "client", "unit": "a supply plan cycle", "work": "plan", "deliver": "hit service levels"},
    ("logistics", "MOVING"): {"client": "customer", "unit": "a household or office move", "work": "move", "deliver": "deliver belongings intact"},
    ("logistics", "E-COMM FULFIL"): {"client": "brand", "unit": "a pick-pack-ship order wave", "work": "wave", "deliver": "ship same-day SLA"},
    ("logistics", "FREIGHT FWDG"): {"client": "shipper", "unit": "a multimodal freight booking", "work": "booking", "deliver": "deliver door-to-door"},
    # ── FINANCE ──
    ("finance", "BANKING"): {"client": "customer", "unit": "an account opening or loan request", "work": "application", "deliver": "activate the account"},
    ("finance", "INSURANCE"): {"client": "policyholder", "unit": "a policy quote or claim", "work": "policy", "deliver": "bind or settle the claim"},
    ("finance", "INVESTMENT"): {"client": "investor", "unit": "an investment mandate", "work": "portfolio", "deliver": "deploy capital"},
    ("finance", "ACCOUNTING"): {"client": "client", "unit": "an audit or tax engagement", "work": "engagement", "deliver": "file on deadline"},
    ("finance", "FINTECH"): {"client": "user", "unit": "an onboarding flow", "work": "account", "deliver": "activate the account"},
    ("finance", "LENDING"): {"client": "borrower", "unit": "a loan application", "work": "loan", "deliver": "fund the loan"},
    ("finance", "WEALTH MGMT"): {"client": "client", "unit": "a wealth review", "work": "portfolio", "deliver": "rebalance to plan"},
    ("finance", "PAYMENTS"): {"client": "merchant", "unit": "a payment integration", "work": "integration", "deliver": "go live on rails"},
    ("finance", "CRYPTO"): {"client": "user", "unit": "a wallet or trade onboarding", "work": "account", "deliver": "enable trading"},
    ("finance", "RISK"): {"client": "client", "unit": "a risk assessment engagement", "work": "assessment", "deliver": "deliver the report"},
    ("finance", "TRADING"): {"client": "client", "unit": "a trade execution request", "work": "trade", "deliver": "execute at best price"},
    ("finance", "MICROFINANCE"): {"client": "borrower", "unit": "a group loan cycle", "work": "cycle", "deliver": "disburse and collect"},
    # ── CONSTRUCTION ──
    ("construction", "RESIDENTIAL"): {"client": "homeowner", "unit": "a home build or remodel", "work": "job", "deliver": "hand over keys"},
    ("construction", "COMMERCIAL"): {"client": "developer", "unit": "a commercial build", "work": "project", "deliver": "substantial completion"},
    ("construction", "INFRASTRUCTURE"): {"client": "agency", "unit": "an infrastructure contract", "work": "project", "deliver": "meet milestone acceptance"},
    ("construction", "ELECTRICAL"): {"client": "GC", "unit": "an electrical scope", "work": "job", "deliver": "pass inspection"},
    ("construction", "PLUMBING"): {"client": "GC", "unit": "a plumbing scope", "work": "job", "deliver": "pass pressure test"},
    ("construction", "INTERIOR"): {"client": "client", "unit": "a fit-out project", "work": "project", "deliver": "hand over finished space"},
    ("construction", "RENOVATION"): {"client": "owner", "unit": "a renovation scope", "work": "job", "deliver": "complete the remodel"},
    ("construction", "DEMOLITION"): {"client": "GC", "unit": "a demolition scope", "work": "job", "deliver": "clear the site"},
    ("construction", "REAL ESTATE"): {"client": "buyer", "unit": "a development project", "work": "project", "deliver": "deliver units for sale"},
    ("construction", "CIVIL ENG"): {"client": "client", "unit": "a civil design package", "work": "design", "deliver": "issue stamped drawings"},
    ("construction", "ENVIRONMENTAL"): {"client": "client", "unit": "an environmental remediation job", "work": "job", "deliver": "meet compliance sign-off"},
    ("construction", "FUEL/ENERGY"): {"client": "operator", "unit": "a fuel or energy site job", "work": "project", "deliver": "commission the system"},
    # ── RETAIL ──
    ("retail", "APPAREL"): {"client": "shopper", "unit": "a seasonal collection drop", "work": "season", "deliver": "move the collection"},
    ("retail", "ELECTRONICS"): {"client": "shopper", "unit": "a device sale", "work": "transaction", "deliver": "complete the sale"},
    ("retail", "GROCERY"): {"client": "shopper", "unit": "your store", "work": "transaction", "deliver": "complete checkout"},
    ("retail", "HARDWARE"): {"client": "shopper", "unit": "a project materials purchase", "work": "transaction", "deliver": "fulfill the order"},
    ("retail", "PHARMACY"): {"client": "patient", "unit": "a prescription fill", "work": "fill", "deliver": "dispense safely"},
    ("retail", "FURNITURE"): {"client": "shopper", "unit": "a furniture order", "work": "order", "deliver": "deliver and assemble"},
    ("retail", "JEWELRY"): {"client": "shopper", "unit": "a custom or high-value piece", "work": "order", "deliver": "deliver with certificate"},
    ("retail", "SPORTING"): {"client": "shopper", "unit": "a gear purchase", "work": "transaction", "deliver": "complete the sale"},
    ("retail", "E-COMMERCE"): {"client": "shopper", "unit": "an online order", "work": "order", "deliver": "fulfill the order"},
    ("retail", "AUTO PARTS"): {"client": "shopper", "unit": "a parts lookup and sale", "work": "transaction", "deliver": "get the right part"},
    ("retail", "BOOKS/STAT"): {"client": "shopper", "unit": "a media or stationery purchase", "work": "transaction", "deliver": "complete checkout"},
    ("retail", "HOME DECOR"): {"client": "shopper", "unit": "a decor purchase", "work": "order", "deliver": "deliver styled goods"},
    # ── EDUCATION ──
    ("education", "K-12"): {"client": "student", "unit": "a term enrollment", "work": "term", "deliver": "report progress"},
    ("education", "HIGHER ED"): {"client": "student", "unit": "a degree program enrollment", "work": "semester", "deliver": "award credits"},
    ("education", "VOCATIONAL"): {"client": "trainee", "unit": "a skills certification program", "work": "cohort", "deliver": "certify completion"},
    ("education", "ED-TECH"): {"client": "learner", "unit": "a course enrollment", "work": "cohort", "deliver": "complete the module"},
    ("education", "CORP TRAINING"): {"client": "employee", "unit": "a training program", "work": "program", "deliver": "demonstrate competency"},
    ("education", "TUTORING"): {"client": "student", "unit": "a tutoring package", "work": "session block", "deliver": "show measurable progress"},
    ("education", "LANGUAGE"): {"client": "learner", "unit": "a language course", "work": "level", "deliver": "pass the level check"},
    ("education", "TEST PREP"): {"client": "student", "unit": "an exam prep program", "work": "prep cycle", "deliver": "hit target score"},
    ("education", "ARTS & MUSIC"): {"client": "student", "unit": "a recital or portfolio term", "work": "term", "deliver": "deliver the performance"},
    ("education", "SPORTS"): {"client": "athlete", "unit": "a training season", "work": "season", "deliver": "peak for competition"},
    ("education", "EARLY CHILD"): {"client": "family", "unit": "an enrollment spot", "work": "term", "deliver": "deliver daily care"},
    ("education", "SPECIAL ED"): {"client": "student", "unit": "an IEP-driven program", "work": "plan cycle", "deliver": "meet IEP goals"},
    # ── ENTERTAINMENT ──
    ("entertainment", "MUSIC"): {"client": "listener", "unit": "a release or tour cycle", "work": "release", "deliver": "drop the track"},
    ("entertainment", "FILM & VIDEO"): {"client": "client", "unit": "a production schedule", "work": "production", "deliver": "deliver the cut"},
    ("entertainment", "GAMING"): {"client": "player", "unit": "a game release cycle", "work": "release", "deliver": "ship the build"},
    ("entertainment", "LIVE EVENTS"): {"client": "attendee", "unit": "a live show or festival", "work": "event", "deliver": "deliver the show"},
    ("entertainment", "STREAMING"): {"client": "subscriber", "unit": "a content season", "work": "season", "deliver": "publish the season"},
    ("entertainment", "SOCIAL MEDIA"): {"client": "follower", "unit": "a content calendar cycle", "work": "campaign", "deliver": "hit engagement targets"},
    ("entertainment", "PUBLISHING"): {"client": "reader", "unit": "a book or issue release", "work": "release", "deliver": "publish on schedule"},
    ("entertainment", "PHOTOGRAPHY"): {"client": "client", "unit": "a shoot booking", "work": "shoot", "deliver": "deliver the gallery"},
    ("entertainment", "ANIMATION"): {"client": "client", "unit": "an animation production", "work": "production", "deliver": "deliver final frames"},
    ("entertainment", "THEATRE"): {"client": "audience", "unit": "a production run", "work": "run", "deliver": "open night"},
    ("entertainment", "SPORTS MEDIA"): {"client": "viewer", "unit": "a broadcast event", "work": "broadcast", "deliver": "go live on air"},
    ("entertainment", "ADVERTISING"): {"client": "brand", "unit": "a campaign production", "work": "campaign", "deliver": "launch the spot"},
}

from s3_conversational_overrides import OVERRIDES
