"""Hand-curated subtype context and stage overrides for Screen 3 flows."""

# client / unit / work / deliver placeholders per subtype
SUBTYPE_CTX = {
    # ── SERVICE ──
    ("service", "IT & TECH"): {"client": "prospect", "unit": "a software build or IT support scope", "work": "project", "deliver": "ship the build"},
    ("service", "CONSULTING"): {"client": "prospect", "unit": "an advisory engagement", "work": "engagement", "deliver": "deliver recommendations"},
    ("service", "LEGAL"): {"client": "potential client", "unit": "a legal matter", "work": "case", "deliver": "close the matter"},
    ("service", "ACCOUNTING"): {"client": "client", "unit": "a tax or bookkeeping scope", "work": "engagement", "deliver": "close the books"},
    ("service", "MARKETING"): {"client": "brand client", "unit": "a campaign scope", "work": "campaign", "deliver": "launch the campaign"},
    ("service", "HEALTHCARE"): {"client": "patient", "unit": "a care appointment or treatment plan", "work": "care plan", "deliver": "deliver care"},
    ("service", "STAFFING"): {"client": "hiring manager", "unit": "an open role requisition", "work": "placement", "deliver": "fill the role"},
    ("service", "CLEANING"): {"client": "client", "unit": "a recurring cleaning contract", "work": "route", "deliver": "complete the clean"},
    ("service", "SECURITY"): {"client": "client", "unit": "a security post or patrol contract", "work": "shift", "deliver": "secure the site"},
    ("service", "HOSPITALITY"): {"client": "guest", "unit": "a room or event booking", "work": "stay", "deliver": "deliver the experience"},
    ("service", "FOOD SERVICE"): {"client": "customer", "unit": "a catering event or service period", "work": "service", "deliver": "serve the event"},
    ("service", "CREATIVE"): {"client": "client", "unit": "a creative brief", "work": "deliverable", "deliver": "deliver the assets"},
    # ── MANUFACTURING ──
    ("manufacturing", "FOOD & BEV"): {"client": "buyer", "unit": "a production batch", "work": "batch", "deliver": "release batch"},
    ("manufacturing", "ELECTRONICS"): {"client": "buyer", "unit": "a production run", "work": "run", "deliver": "ship units"},
    ("manufacturing", "TEXTILES"): {"client": "buyer", "unit": "a fabric production lot", "work": "lot", "deliver": "ship the roll"},
    ("manufacturing", "CHEMICALS"): {"client": "buyer", "unit": "a chemical batch", "work": "batch", "deliver": "release to spec"},
    ("manufacturing", "METAL & STEEL"): {"client": "buyer", "unit": "a fabrication order", "work": "order", "deliver": "deliver fabricated parts"},
    ("manufacturing", "AUTOMOTIVE"): {"client": "OEM", "unit": "a parts production run", "work": "run", "deliver": "ship to line"},
    ("manufacturing", "FURNITURE"): {"client": "buyer", "unit": "a furniture production order", "work": "order", "deliver": "ship finished goods"},
    ("manufacturing", "MEDICAL"): {"client": "buyer", "unit": "a regulated device batch", "work": "batch", "deliver": "release with documentation"},
    ("manufacturing", "CONSTRUCTION"): {"client": "contractor", "unit": "a materials production order", "work": "order", "deliver": "deliver to site"},
    ("manufacturing", "PLASTICS"): {"client": "buyer", "unit": "an injection molding run", "work": "run", "deliver": "ship molded parts"},
    ("manufacturing", "PRINT & PAPER"): {"client": "buyer", "unit": "a print production job", "work": "job", "deliver": "deliver the print run"},
    ("manufacturing", "AGRI-PROC"): {"client": "buyer", "unit": "a processing batch", "work": "batch", "deliver": "release packaged goods"},
    # ── AGRICULTURE ──
    ("agriculture", "CROP FARMING"): {"client": "buyer", "unit": "a harvest lot", "work": "season", "deliver": "move the crop"},
    ("agriculture", "LIVESTOCK"): {"client": "buyer", "unit": "a livestock lot", "work": "herd cycle", "deliver": "deliver animals or meat"},
    ("agriculture", "DAIRY"): {"client": "buyer", "unit": "a daily milk collection", "work": "collection", "deliver": "deliver milk"},
    ("agriculture", "POULTRY"): {"client": "buyer", "unit": "a flock batch", "work": "flock cycle", "deliver": "process and ship"},
    ("agriculture", "AQUACULTURE"): {"client": "buyer", "unit": "a pond or tank harvest", "work": "harvest", "deliver": "ship fresh stock"},
    ("agriculture", "HORTICULTURE"): {"client": "buyer", "unit": "a greenhouse harvest", "work": "harvest", "deliver": "deliver produce"},
    ("agriculture", "ORGANIC"): {"client": "buyer", "unit": "a certified organic lot", "work": "season", "deliver": "deliver certified produce"},
    ("agriculture", "PROCESSING"): {"client": "buyer", "unit": "a value-add processing run", "work": "run", "deliver": "ship packaged goods"},
    ("agriculture", "PLANTATION"): {"client": "buyer", "unit": "a plantation harvest", "work": "harvest", "deliver": "process and export"},
    ("agriculture", "SEED SUPPLY"): {"client": "farmer", "unit": "a seed or input order", "work": "order", "deliver": "deliver inputs on time"},
    ("agriculture", "IRRIGATION"): {"client": "farmer", "unit": "an irrigation install or service", "work": "project", "deliver": "commission the system"},
    ("agriculture", "EXPORT/TRADE"): {"client": "importer", "unit": "an export shipment", "work": "shipment", "deliver": "clear customs and deliver"},
    # ── LOGISTICS ──
    ("logistics", "ROAD/TRUCKING"): {"client": "shipper", "unit": "a full truckload", "work": "load", "deliver": "deliver on time"},
    ("logistics", "AIR FREIGHT"): {"client": "shipper", "unit": "an air cargo booking", "work": "consignment", "deliver": "deliver to consignee"},
    ("logistics", "SEA/OCEAN"): {"client": "shipper", "unit": "a container booking", "work": "shipment", "deliver": "release at port"},
    ("logistics", "RAIL"): {"client": "shipper", "unit": "a rail car load", "work": "consignment", "deliver": "deliver at terminal"},
    ("logistics", "WAREHOUSING"): {"client": "client", "unit": "an inbound inventory batch", "work": "fulfillment wave", "deliver": "ship orders"},
    ("logistics", "LAST MILE"): {"client": "customer", "unit": "a same-day delivery", "work": "route", "deliver": "complete delivery"},
    ("logistics", "COLD CHAIN"): {"client": "shipper", "unit": "a temperature-sensitive shipment", "work": "load", "deliver": "deliver in-spec"},
    ("logistics", "CUSTOMS"): {"client": "importer", "unit": "a customs clearance file", "work": "clearance", "deliver": "release shipment"},
    ("logistics", "SUPPLY CHAIN"): {"client": "client", "unit": "a supply plan cycle", "work": "plan", "deliver": "hit service levels"},
    ("logistics", "MOVING"): {"client": "customer", "unit": "a household or office move", "work": "move", "deliver": "deliver belongings intact"},
    ("logistics", "E-COMM FULFIL"): {"client": "brand", "unit": "a pick-pack-ship order wave", "work": "wave", "deliver": "ship same-day SLA"},
    ("logistics", "FREIGHT FWDG"): {"client": "shipper", "unit": "a multimodal freight booking", "work": "booking", "deliver": "deliver door-to-door"},
    # ── FINANCE ──
    ("finance", "BANKING"): {"client": "customer", "unit": "an account opening or loan request", "work": "application", "deliver": "activate the account"},
    ("finance", "INSURANCE"): {"client": "policyholder", "unit": "a policy quote or claim", "work": "policy", "deliver": "bind or settle the claim"},
    ("finance", "INVESTMENT"): {"client": "investor", "unit": "an investment mandate", "work": "portfolio", "deliver": "deploy capital"},
    ("finance", "ACCOUNTING"): {"client": "client", "unit": "an audit or tax engagement", "work": "engagement", "deliver": "file on deadline"},
    ("finance", "FINTECH"): {"client": "user", "unit": "an onboarding flow", "work": "account", "deliver": "activate the account"},
    ("finance", "LENDING"): {"client": "borrower", "unit": "a loan application", "work": "loan", "deliver": "fund the loan"},
    ("finance", "WEALTH MGMT"): {"client": "client", "unit": "a wealth review", "work": "portfolio", "deliver": "rebalance to plan"},
    ("finance", "PAYMENTS"): {"client": "merchant", "unit": "a payment integration", "work": "integration", "deliver": "go live on rails"},
    ("finance", "CRYPTO"): {"client": "user", "unit": "a wallet or trade onboarding", "work": "account", "deliver": "enable trading"},
    ("finance", "RISK"): {"client": "client", "unit": "a risk assessment engagement", "work": "assessment", "deliver": "deliver the report"},
    ("finance", "TRADING"): {"client": "client", "unit": "a trade execution request", "work": "trade", "deliver": "execute at best price"},
    ("finance", "MICROFINANCE"): {"client": "borrower", "unit": "a group loan cycle", "work": "cycle", "deliver": "disburse and collect"},
    # ── CONSTRUCTION ──
    ("construction", "RESIDENTIAL"): {"client": "homeowner", "unit": "a home build or remodel", "work": "job", "deliver": "hand over keys"},
    ("construction", "COMMERCIAL"): {"client": "developer", "unit": "a commercial build", "work": "project", "deliver": "substantial completion"},
    ("construction", "INFRASTRUCTURE"): {"client": "agency", "unit": "an infrastructure contract", "work": "project", "deliver": "meet milestone acceptance"},
    ("construction", "ELECTRICAL"): {"client": "GC", "unit": "an electrical scope", "work": "job", "deliver": "pass inspection"},
    ("construction", "PLUMBING"): {"client": "GC", "unit": "a plumbing scope", "work": "job", "deliver": "pass pressure test"},
    ("construction", "INTERIOR"): {"client": "client", "unit": "a fit-out project", "work": "project", "deliver": "hand over finished space"},
    ("construction", "RENOVATION"): {"client": "owner", "unit": "a renovation scope", "work": "job", "deliver": "complete the remodel"},
    ("construction", "DEMOLITION"): {"client": "GC", "unit": "a demolition scope", "work": "job", "deliver": "clear the site"},
    ("construction", "REAL ESTATE"): {"client": "buyer", "unit": "a development project", "work": "project", "deliver": "deliver units for sale"},
    ("construction", "CIVIL ENG"): {"client": "client", "unit": "a civil design package", "work": "design", "deliver": "issue stamped drawings"},
    ("construction", "ENVIRONMENTAL"): {"client": "client", "unit": "an environmental remediation job", "work": "job", "deliver": "meet compliance sign-off"},
    ("construction", "FUEL/ENERGY"): {"client": "operator", "unit": "a fuel or energy site job", "work": "project", "deliver": "commission the system"},
    # ── RETAIL ──
    ("retail", "APPAREL"): {"client": "shopper", "unit": "a seasonal collection drop", "work": "season", "deliver": "move the collection"},
    ("retail", "ELECTRONICS"): {"client": "shopper", "unit": "a device sale", "work": "transaction", "deliver": "complete the sale"},
    ("retail", "GROCERY"): {"client": "shopper", "unit": "a basket of goods", "work": "transaction", "deliver": "complete checkout"},
    ("retail", "HARDWARE"): {"client": "shopper", "unit": "a project materials purchase", "work": "transaction", "deliver": "fulfill the order"},
    ("retail", "PHARMACY"): {"client": "patient", "unit": "a prescription fill", "work": "fill", "deliver": "dispense safely"},
    ("retail", "FURNITURE"): {"client": "shopper", "unit": "a furniture order", "work": "order", "deliver": "deliver and assemble"},
    ("retail", "JEWELRY"): {"client": "shopper", "unit": "a custom or high-value piece", "work": "order", "deliver": "deliver with certificate"},
    ("retail", "SPORTING"): {"client": "shopper", "unit": "a gear purchase", "work": "transaction", "deliver": "complete the sale"},
    ("retail", "E-COMMERCE"): {"client": "shopper", "unit": "an online order", "work": "order", "deliver": "fulfill the order"},
    ("retail", "AUTO PARTS"): {"client": "shopper", "unit": "a parts lookup and sale", "work": "transaction", "deliver": "get the right part"},
    ("retail", "BOOKS/STAT"): {"client": "shopper", "unit": "a media or stationery purchase", "work": "transaction", "deliver": "complete checkout"},
    ("retail", "HOME DECOR"): {"client": "shopper", "unit": "a decor purchase", "work": "order", "deliver": "deliver styled goods"},
    # ── EDUCATION ──
    ("education", "K-12"): {"client": "student", "unit": "a term enrollment", "work": "term", "deliver": "report progress"},
    ("education", "HIGHER ED"): {"client": "student", "unit": "a degree program enrollment", "work": "semester", "deliver": "award credits"},
    ("education", "VOCATIONAL"): {"client": "trainee", "unit": "a skills certification program", "work": "cohort", "deliver": "certify completion"},
    ("education", "ED-TECH"): {"client": "learner", "unit": "a course enrollment", "work": "cohort", "deliver": "complete the module"},
    ("education", "CORP TRAINING"): {"client": "employee", "unit": "a training program", "work": "program", "deliver": "demonstrate competency"},
    ("education", "TUTORING"): {"client": "student", "unit": "a tutoring package", "work": "session block", "deliver": "show measurable progress"},
    ("education", "LANGUAGE"): {"client": "learner", "unit": "a language course", "work": "level", "deliver": "pass the level check"},
    ("education", "TEST PREP"): {"client": "student", "unit": "an exam prep program", "work": "prep cycle", "deliver": "hit target score"},
    ("education", "ARTS & MUSIC"): {"client": "student", "unit": "a recital or portfolio term", "work": "term", "deliver": "deliver the performance"},
    ("education", "SPORTS"): {"client": "athlete", "unit": "a training season", "work": "season", "deliver": "peak for competition"},
    ("education", "EARLY CHILD"): {"client": "family", "unit": "an enrollment spot", "work": "term", "deliver": "deliver daily care"},
    ("education", "SPECIAL ED"): {"client": "student", "unit": "an IEP-driven program", "work": "plan cycle", "deliver": "meet IEP goals"},
    # ── ENTERTAINMENT ──
    ("entertainment", "MUSIC"): {"client": "listener", "unit": "a release or tour cycle", "work": "release", "deliver": "drop the track"},
    ("entertainment", "FILM & VIDEO"): {"client": "client", "unit": "a production schedule", "work": "production", "deliver": "deliver the cut"},
    ("entertainment", "GAMING"): {"client": "player", "unit": "a game release cycle", "work": "release", "deliver": "ship the build"},
    ("entertainment", "LIVE EVENTS"): {"client": "attendee", "unit": "a live show or festival", "work": "event", "deliver": "deliver the show"},
    ("entertainment", "STREAMING"): {"client": "subscriber", "unit": "a content season", "work": "season", "deliver": "publish the season"},
    ("entertainment", "SOCIAL MEDIA"): {"client": "follower", "unit": "a content calendar cycle", "work": "campaign", "deliver": "hit engagement targets"},
    ("entertainment", "PUBLISHING"): {"client": "reader", "unit": "a book or issue release", "work": "release", "deliver": "publish on schedule"},
    ("entertainment", "PHOTOGRAPHY"): {"client": "client", "unit": "a shoot booking", "work": "shoot", "deliver": "deliver the gallery"},
    ("entertainment", "ANIMATION"): {"client": "client", "unit": "an animation production", "work": "production", "deliver": "deliver final frames"},
    ("entertainment", "THEATRE"): {"client": "audience", "unit": "a production run", "work": "run", "deliver": "open night"},
    ("entertainment", "SPORTS MEDIA"): {"client": "viewer", "unit": "a broadcast event", "work": "broadcast", "deliver": "go live on air"},
    ("entertainment", "ADVERTISING"): {"client": "brand", "unit": "a campaign production", "work": "campaign", "deliver": "launch the spot"},
}

# Stage index → partial stage override (q, opts, states, diag, fix, name)
OVERRIDES = {
    # SERVICE
    ("service", "IT & TECH"): {0: {"q": "A SaaS lead hits your site today. How did they find you and get logged?",
        "opts": ["Attribution tracked — source, form, and CRM entry automatic.", "We log leads but source tracking is patchy.", "Leads sit in inbox and Slack — no single pipeline."],
        "fix": "Marketing attribution + CRM intake"}},
    ("service", "CONSULTING"): {1: {"q": "A CEO wants help with {unit}. How do you scope before proposing fees?",
        "opts": ["Structured discovery workshop with documented outcomes.", "A call and a rough scope doc.", "We propose first and refine scope after sign-on."],
        "fix": "Discovery framework + SOW templates"}},
    ("service", "LEGAL"): {1: {"q": "A potential client describes {unit}. How do you scope before quoting fees?",
        "opts": ["Conflict check + intake form before any fee quote.", "Verbal scope on a call, then a letter.", "We quote a retainer and figure details out later."],
        "fix": "Legal intake + conflict workflow"}},
    ("service", "ACCOUNTING"): {4: {"q": "Month-end close for {unit} — how is billing handled?",
        "opts": ["Recurring invoices and WIP tracked to milestones.", "We bill when the partner remembers.", "Some client work never makes it to an invoice."],
        "fix": "WIP tracking + recurring billing"}},
    ("service", "MARKETING"): {0: {"q": "A brand wants {unit}. How do you capture and qualify the lead?",
        "opts": ["Brief intake form with budget, timeline, and ICP logged.", "Email back-and-forth until we understand scope.", "We start pitching before requirements are clear."],
        "fix": "Creative brief intake + CRM"}},
    ("service", "HEALTHCARE"): {0: {"q": "A new {client} needs {unit}. How is intake handled?",
        "opts": ["EHR/scheduling captures intake with insurance verified.", "Front desk notes it — verification happens later.", "Patients wait while we hunt for records."],
        "fix": "Patient intake + eligibility check"}},
    ("service", "STAFFING"): {0: {"q": "A {client} sends {unit}. How fast do you log and match candidates?",
        "opts": ["Req logged in ATS with match score within hours.", "We search our spreadsheet when we have time.", "We rely on memory of who might fit."],
        "fix": "ATS + candidate matching"}},
    ("service", "CLEANING"): {3: {"q": "Tonight's {work} across multiple sites — how is completion verified?",
        "opts": ["Checklists + photos synced from each site in real time.", "Supervisor drives by when they can.", "Clients tell us if something was missed."],
        "fix": "Mobile checklists + photo proof"}},
    ("service", "SECURITY"): {3: {"q": "An incident on {work} — how is it reported and escalated?",
        "opts": ["Incident logged in real time with escalation protocol.", "Guard calls supervisor — report filed later.", "We hear about it from the client the next day."],
        "fix": "Incident reporting + dispatch"}},
    ("service", "HOSPITALITY"): {0: {"q": "A {client} wants {unit}. How is the booking captured?",
        "opts": ["PMS/CRM logs source, preferences, and upsell history.", "Booking logged but guest history is fragmented.", "Bookings live in phone notes and memory."],
        "fix": "PMS + guest profile CRM"}},
    ("service", "FOOD SERVICE"): {2: {"q": "A large {unit} is tomorrow. How is prep and staffing coordinated?",
        "opts": ["Prep lists, par levels, and staff roster in one system.", "Head chef coordinates by text and whiteboard.", "We scramble the morning of the event."],
        "fix": "Event prep + kitchen ops system"}},
    ("service", "CREATIVE"): {2: {"q": "A {client} approved {unit}. How fast do you send the contract and deposit invoice?",
        "opts": ["Contract + deposit link sent same day from template.", "Custom contract drafted over several days.", "Work starts before paperwork is signed."],
        "fix": "Contract templates + deposit automation"}},
    # MANUFACTURING
    ("manufacturing", "FOOD & BEV"): {2: {"q": "On the line for {unit}, how is food safety monitored?",
        "opts": ["HACCP logs and batch traceability in real time.", "Checks done but records are partly paper.", "Issues surface at customer complaint or audit."],
        "diag": {"shaky": "Partial digital records slow recalls and increase scrap.", "missing": "Weak food safety tracking is a recall waiting to happen."},
        "fix": "HACCP + traceability system"}},
    ("manufacturing", "ELECTRONICS"): {2: {"q": "Mid-{work}, a component fails AOI/SPC limits. What happens?",
        "opts": ["Defect logged, lot held, root cause tracked digitally.", "Line stops and we fix it — records are informal.", "Bad units ship until the customer rejects them."],
        "fix": "SPC + defect traceability"}},
    ("manufacturing", "TEXTILES"): {1: {"q": "Before weaving {unit}, how is dye and loom scheduling planned?",
        "opts": ["MRP drives loom allocation and dye lot matching.", "Planner builds schedule in spreadsheets.", "We run whatever color the customer yelled about last."],
        "fix": "Textile MRP + loom scheduling"}},
    ("manufacturing", "CHEMICALS"): {2: {"q": "During {unit} production, how are batch records and safety kept?",
        "opts": ["Electronic batch records with deviation alerts.", "Paper logbooks with supervisor sign-off.", "Deviations discovered at release testing."],
        "fix": "EBR + deviation management"}},
    ("manufacturing", "METAL & STEEL"): {1: {"q": "A rush {unit} hits the floor. How is capacity and sequence planned?",
        "opts": ["Finite scheduling with heat treat and weld queue visible.", "Foreman sequences jobs on a whiteboard.", "Loudest customer gets bumped to the front."],
        "fix": "Finite capacity scheduling"}},
    ("manufacturing", "AUTOMOTIVE"): {2: {"q": "An OEM flags a quality concern on {unit}. How fast can you trace the lot?",
        "opts": ["Full genealogy trace in minutes — serial to supplier lot.", "We can trace but it takes a day of digging.", "Traceability gaps mean we can't isolate the lot."],
        "fix": "Automotive traceability + PPAP"}},
    ("manufacturing", "FURNITURE"): {3: {"q": "Finished {unit} ready — how is pick, pack, and ship coordinated?",
        "opts": ["WMS tracks SKU, carton, and carrier booking.", "Warehouse coordinates by walkie-talkie.", "Shipments leave when someone finds a truck."],
        "fix": "WMS + carrier integration"}},
    ("manufacturing", "MEDICAL"): {2: {"q": "Releasing {unit} — how is device history and UDI handled?",
        "opts": ["DHR complete with UDI assigned before release.", "DHR mostly done — gaps filled if auditor asks.", "Release happens before documentation catches up."],
        "fix": "DHR + UDI compliance system"}},
    ("manufacturing", "CONSTRUCTION"): {1: {"q": "A GC orders {unit} for a job site. How is production scheduled?",
        "opts": ["Job-linked production with delivery window locked.", "We produce to stock and hope timing works.", "Site calls when they're out — we rush it."],
        "fix": "Job-linked production scheduling"}},
    ("manufacturing", "PLASTICS"): {2: {"q": "Mid-{work}, cavity wear shifts dimensions. How is it caught?",
        "opts": ["SPC charts trigger hold before bad parts accumulate.", "Operator notices and adjusts — not always logged.", "Customer returns tell us the mold was worn."],
        "fix": "SPC + mold maintenance tracking"}},
    ("manufacturing", "PRINT & PAPER"): {2: {"q": "Color drift mid-{work}. How is quality verified before ship?",
        "opts": ["Spectro readings logged against proof — auto hold on drift.", "Operator eyeballs against last good sheet.", "Customer rejects the run after delivery."],
        "fix": "Color management + QA holds"}},
    ("manufacturing", "AGRI-PROC"): {2: {"q": "Processing {unit} — how is moisture/grade and traceability tracked?",
        "opts": ["Lot grading and moisture logged at each process step.", "Final check before bagging — mid-process is informal.", "Buyers reject lots we can't trace to source."],
        "fix": "Lot grading + traceability"}},
    # AGRICULTURE
    ("agriculture", "CROP FARMING"): {2: {"q": "Mid-{work} on {unit}, how do you monitor crop health and inputs?",
        "opts": ["Soil moisture, NDVI, and spray logs in one dashboard.", "Scouting walks — notes in a field notebook.", "Crop stress visible from the road before we act."],
        "fix": "Precision ag monitoring"}},
    ("agriculture", "LIVESTOCK"): {2: {"q": "During {work}, how do you track animal health and feed?",
        "opts": ["Herd management system with health alerts.", "Daily walk-through — issues logged on paper.", "We notice problems when weight gain stalls."],
        "fix": "Herd management + health alerts"}},
    ("agriculture", "DAIRY"): {2: {"q": "At {work} time, how is milk quality and cold chain monitored?",
        "opts": ["SCC, temp, and tank readings logged automatically.", "Quality checked at pickup — between checks is blind.", "Rejected loads tell us something went wrong."],
        "fix": "Milk quality + tank monitoring"}},
    ("agriculture", "POULTRY"): {2: {"q": "Mid-{work}, how are mortality, feed, and biosecurity tracked?",
        "opts": ["Flock logs with mortality alerts and biosecurity checklist.", "House checks recorded on clipboards.", "Disease shows up before numbers tell the story."],
        "fix": "Flock management + biosecurity"}},
    ("agriculture", "AQUACULTURE"): {2: {"q": "Water quality on {unit} — how is it monitored?",
        "opts": ["DO, pH, and ammonia logged with alert thresholds.", "Manual tests once or twice daily.", "Fish loss is the first sign something's off."],
        "fix": "Aquaculture water monitoring"}},
    ("agriculture", "HORTICULTURE"): {2: {"q": "Greenhouse {unit} — how are climate and irrigation controlled?",
        "opts": ["Automated climate/irrigation with daily dashboards.", "Manual adjustments when plants look stressed.", "Crop loss before we find the settings error."],
        "fix": "Greenhouse automation + alerts"}},
    ("agriculture", "ORGANIC"): {1: {"q": "Planning {work} — how do you track organic inputs and certification?",
        "opts": ["Input ledger tied to cert body requirements.", "Mostly compliant — records assembled before audit.", "Certifier findings surprise us at inspection."],
        "fix": "Organic compliance ledger"}},
    ("agriculture", "PROCESSING"): {2: {"q": "Running {unit} — how is lot traceability from farm to package maintained?",
        "opts": ["Farm lot linked through every process step digitally.", "Lot numbers on paper — reconciliation takes hours.", "Recall would be a nightmare — traceability gaps."],
        "fix": "Farm-to-package traceability"}},
    ("agriculture", "PLANTATION"): {3: {"q": "Harvest day for {unit} — how is field-to-factory flow coordinated?",
        "opts": ["Harvest crews, transport, and mill intake scheduled as one chain.", "Field and factory coordinate by radio.", "Cherry sits too long — quality degrades before processing."],
        "fix": "Harvest logistics coordination"}},
    ("agriculture", "SEED SUPPLY"): {0: {"q": "A {client} orders {unit}. How is variety, quantity, and delivery tracked?",
        "opts": ["Order system with germination certs and delivery window.", "Phone order written on a pad.", "Wrong variety shipped — caught when farmer plants."],
        "fix": "Seed order + cert tracking"}},
    ("agriculture", "IRRIGATION"): {3: {"q": "Commissioning {unit} — how is install progress and sign-off tracked?",
        "opts": ["Install checklist with photos and flow test results logged.", "Foreman signs off verbally at end of day.", "Farmer finds leaks weeks after we left."],
        "fix": "Install QA + sign-off workflow"}},
    ("agriculture", "EXPORT/TRADE"): {3: {"q": "Exporting {unit} — how are phytosanitary docs and shipment tracked?",
        "opts": ["Export docs, container, and vessel tracked end-to-end.", "Docs assembled at port under time pressure.", "Shipment held — paperwork missing at customs."],
        "fix": "Export documentation workflow"}},
    # LOGISTICS
    ("logistics", "ROAD/TRUCKING"): {1: {"q": "Dispatching {unit} — how are driver hours and route assigned?",
        "opts": ["TMS assigns route with HOS compliance checked.", "Dispatcher picks driver from experience.", "Driver choice + paper logs — compliance is shaky."],
        "fix": "TMS + HOS compliance"}},
    ("logistics", "AIR FREIGHT"): {1: {"q": "Booking {unit} — how do cutoffs, AWB, and capacity get coordinated?",
        "opts": ["Air freight platform books space with cutoff alerts.", "Agent emails back and forth until confirmed.", "Missed cutoff — shipment rolls to next flight."],
        "fix": "Air freight booking platform"}},
    ("logistics", "SEA/OCEAN"): {1: {"q": "Booking {unit} — how are vessel, container, and cutoffs managed?",
        "opts": ["Ocean booking with SI/VGM and cutoff tracking.", "Forwarder handles it — we find out status late.", "Rolled container — no visibility until it's too late."],
        "fix": "Ocean booking + cutoff alerts"}},
    ("logistics", "RAIL"): {2: {"q": "{unit} on rail — can you see location and ETA?",
        "opts": ["Rail tracking integrated with intermodal milestones.", "Terminal calls when car arrives.", "Consignee asks — we don't know where the car is."],
        "fix": "Rail visibility + intermodal tracking"}},
    ("logistics", "WAREHOUSING"): {3: {"q": "Pick wave for {unit} — how is accuracy and SLA tracked?",
        "opts": ["WMS scan-verify with pick rate and error dashboards.", "Pickers know the floor — errors found at pack.", "Wrong SKU shipped — customer returns tell us."],
        "fix": "Scan-verify WMS"}},
    ("logistics", "LAST MILE"): {1: {"q": "Same-day {unit} — how are routes and driver stops optimized?",
        "opts": ["Dynamic routing with live re-sequencing for traffic.", "Static route built once in the morning.", "Drivers reroute themselves — ETAs are guesses."],
        "fix": "Dynamic last-mile routing"}},
    ("logistics", "COLD CHAIN"): {2: {"q": "A temperature-sensitive {unit} is moving. Can you see breach risk in real time?",
        "opts": ["Live temp sensors with alert thresholds at every handoff.", "Driver checks temps at stops and texts updates.", "We find out about a breach from the receiver."],
        "diag": {"shaky": "Manual temp checks miss handoff gaps where product spoils.", "missing": "No continuous monitoring makes claims and losses inevitable."},
        "fix": "Continuous temp monitoring"}},
    ("logistics", "CUSTOMS"): {0: {"q": "An importer sends documents for {unit}. How is clearance intake handled?",
        "opts": ["Document checklist with HS codes validated before filing.", "Broker receives docs and files when complete.", "Shipment arrives — docs still being assembled."],
        "fix": "Customs doc intake + validation"}},
    ("logistics", "SUPPLY CHAIN"): {1: {"q": "Planning {unit} — how do you balance inventory, service level, and cost?",
        "opts": ["S&OP with demand forecast and safety stock modeled.", "Spreadsheet plan updated monthly.", "We react when stockouts or excess hit."],
        "fix": "S&OP + demand planning"}},
    ("logistics", "MOVING"): {2: {"q": "During {work}, how is inventory condition and location tracked?",
        "opts": ["Barcode inventory with condition notes at load/unload.", "Crew notes damage on paper at delivery.", "Missing items discovered when customer unpacks."],
        "fix": "Moving inventory tracking"}},
    ("logistics", "E-COMM FULFIL"): {3: {"q": "SLA pick-pack-ship for {unit} — how is same-day performance tracked?",
        "opts": ["Wave SLA dashboard with cut-off alerts and scan milestones.", "We hit SLA most days — no live dashboard.", "Missed cutoffs discovered at end of shift."],
        "fix": "Fulfillment SLA dashboard"}},
    ("logistics", "FREIGHT FWDG"): {1: {"q": "Multimodal {unit} — how are legs, docs, and handoffs coordinated?",
        "opts": ["Single shipment record tracks every leg and document.", "Each leg managed separately — status in silos.", "Customer asks for ETA — we chase multiple parties."],
        "fix": "Multimodal shipment hub"}},
    # FINANCE
    ("finance", "BANKING"): {1: {"q": "Opening {unit} — how is KYC and risk scoring handled?",
        "opts": ["Digital KYC with automated risk tier and approval routing.", "Branch collects docs — back office processes later.", "Account opened — compliance gaps found in audit."],
        "fix": "Digital KYC + risk routing"}},
    ("finance", "INSURANCE"): {4: {"q": "A claim on {unit} comes in. How is it triaged and settled?",
        "opts": ["Claims portal with FNOL, adjuster assignment, and SLA.", "Email/Fax claim — adjuster picks it up when free.", "Claimant calls repeatedly — no status visibility."],
        "fix": "Claims management portal"}},
    ("finance", "INVESTMENT"): {3: {"q": "{client} approves {unit}. How is capital deployed and reported?",
        "opts": ["Order management with same-day allocation reporting.", "Trades placed — client report comes later.", "Client asks for holdings — we pull from multiple systems."],
        "fix": "Portfolio order management"}},
    ("finance", "ACCOUNTING"): {4: {"q": "Engagement work on {unit} done — when does the client get billed?",
        "opts": ["Time and WIP convert to invoice on milestone.", "Partner batches invoices monthly.", "Work done — invoice still sitting in WIP."],
        "fix": "WIP-to-invoice automation"}},
    ("finance", "FINTECH"): {2: {"q": "A user completes KYC for {unit}. How fast is the account activated?",
        "opts": ["Automated KYC decision with instant activation path.", "Manual review queue — activation same day if lucky.", "Users stuck in pending — support tickets pile up."],
        "fix": "Automated KYC + activation"}},
    ("finance", "LENDING"): {1: {"q": "A {client} applies for {unit}. How is credit decisioned?",
        "opts": ["Credit model with doc upload and decision in hours.", "Underwriter reviews stack manually over days.", "Approved on gut — portfolio risk is opaque."],
        "fix": "Digital underwriting workflow"}},
    ("finance", "WEALTH MGMT"): {5: {"q": "Annual review for {client} — how is the {unit} conversation prepared?",
        "opts": ["Review pack auto-generated with performance vs. IPS.", "Advisor builds deck manually before each meeting.", "Client asks questions we can't answer without digging."],
        "fix": "Client review automation"}},
    ("finance", "PAYMENTS"): {3: {"q": "Merchant going live on {unit} — how is integration tested and monitored?",
        "opts": ["Sandbox-to-prod checklist with transaction monitoring live.", "Go-live after dev says it's ready.", "Merchant finds bugs in production — chargebacks spike."],
        "fix": "Integration QA + txn monitoring"}},
    ("finance", "CRYPTO"): {1: {"q": "User onboarding for {unit} — how are KYC, wallet, and travel rule handled?",
        "opts": ["Compliance checks automated with wallet provisioning tracked.", "Manual KYC then wallet created by ops.", "Compliance gaps found when regulator asks."],
        "fix": "Crypto compliance + wallet ops"}},
    ("finance", "RISK"): {1: {"q": "Scoping {unit} — how is data collection and control testing organized?",
        "opts": ["Engagement portal with request list and evidence tracking.", "Email requests — chase evidence for weeks.", "Report due — testing still not complete."],
        "fix": "Audit/risk engagement portal"}},
    ("finance", "TRADING"): {3: {"q": "Executing {unit} — how are orders, fills, and best execution tracked?",
        "opts": ["OMS with fill reporting and best-ex audit trail.", "Orders sent — fills reconciled end of day.", "Client disputes fill — we can't reconstruct the tape."],
        "fix": "OMS + best-ex reporting"}},
    ("finance", "MICROFINANCE"): {4: {"q": "End of {work} — how are repayments collected and recorded?",
        "opts": ["Field app logs collection with group ledger updated live.", "Agent collects cash — ledger updated back at branch.", "Arrears discovered when group meeting happens."],
        "fix": "Field collection + group ledger app"}},
    # CONSTRUCTION
    ("construction", "RESIDENTIAL"): {3: {"q": "On the {work} site, how is daily progress and schedule tracked?",
        "opts": ["Daily log, photos, and schedule in one platform.", "Foreman texts end-of-day update.", "Homeowner hears about delays before we do."],
        "fix": "Residential job tracking"}},
    ("construction", "COMMERCIAL"): {3: {"q": "Commercial {work} — how are RFIs, submittals, and schedule managed?",
        "opts": ["Procore/equivalent with RFI turnaround tracked.", "Email RFIs — schedule in a shared spreadsheet.", "RFI backlog delays critical path silently."],
        "fix": "Construction PM platform"}},
    ("construction", "INFRASTRUCTURE"): {3: {"q": "Public {work} — how are inspections, safety, and progress documented?",
        "opts": ["Daily safety + progress logs with inspection sign-offs digital.", "Paper logs — inspector copies upon request.", "Failed inspection stops work — docs weren't ready."],
        "fix": "Infrastructure compliance logging"}},
    ("construction", "ELECTRICAL"): {3: {"q": "Rough-in on {work} — how are wire pulls, tests, and inspections tracked?",
        "opts": ["Circuit map + test results logged before cover-up.", "Foreman knows what's done — records are partial.", "Failed inspection — rework behind drywall."],
        "fix": "Electrical QA + inspection log"}},
    ("construction", "PLUMBING"): {3: {"q": "Pressure test on {work} — how is sign-off documented?",
        "opts": ["Test results and photos logged before close-in.", "Test passed — paperwork filed later.", "Leak found after drywall — no test record."],
        "fix": "Plumbing test documentation"}},
    ("construction", "INTERIOR"): {2: {"q": "Client approved {unit}. How fast is contract and deposit processed?",
        "opts": ["Design contract + deposit sent for e-sign same day.", "Custom contract takes a week.", "Work starts before selections are fully signed."],
        "fix": "Interior contract + deposit flow"}},
    ("construction", "RENOVATION"): {1: {"q": "Scoping {unit} in an occupied space — how is existing condition captured?",
        "opts": ["Photo survey + scope doc before pricing.", "Walk-through notes and verbal assumptions.", "Hidden conditions blow the budget mid-job."],
        "fix": "Renovation scope capture"}},
    ("construction", "DEMOLITION"): {1: {"q": "Before {work}, how are hazmat survey and permits verified?",
        "opts": ["Pre-demo checklist with hazmat and permit sign-off logged.", "We start demo — permits chased in parallel.", "Stop-work order — permit or hazmat gap."],
        "fix": "Pre-demo compliance checklist"}},
    ("construction", "REAL ESTATE"): {0: {"q": "A new {unit} opportunity — how is feasibility tracked?",
        "opts": ["Deal pipeline with pro forma and entitlement milestones.", "Spreadsheet for active deals — rest in memory.", "Pursue deals reactively — no pipeline view."],
        "fix": "Development deal pipeline"}},
    ("construction", "CIVIL ENG"): {2: {"q": "Design for {unit} — how are revisions and submittals controlled?",
        "opts": ["Version-controlled drawings with transmittal log.", "Latest file in email thread is 'current'.", "Contractor builds from wrong revision."],
        "fix": "Drawing control + transmittals"}},
    ("construction", "ENVIRONMENTAL"): {3: {"q": "Remediation {work} — how is sampling and compliance reported?",
        "opts": ["Sample chain-of-custody and progress reports on schedule.", "Lab results filed when they arrive.", "Regulator asks for data we can't produce quickly."],
        "fix": "Environmental data management"}},
    ("construction", "FUEL/ENERGY"): {1: {"q": "A fuel/energy site job — how do you estimate compliance and scope?",
        "opts": ["Compliance checklist built into estimate before bid.", "Compliance cost estimated as a line item guess.", "Compliance change orders eat margin mid-project."],
        "fix": "Compliance-aware estimating"}},
    # RETAIL
    ("retail", "APPAREL"): {1: {"q": "New {unit} arriving — how are size curves and floor allocation planned?",
        "opts": ["Size pack and allocation driven by sell-through data.", "Buyer's instinct — allocation adjusted after launch.", "Wrong sizes on floor — markdowns start early."],
        "fix": "Allocation + size curve analytics"}},
    ("retail", "ELECTRONICS"): {1: {"q": "High-value {unit} on shelf — how is serial, warranty, and stock tracked?",
        "opts": ["Serial-tracked inventory with activation at POS.", "Stock count periodic — serials tracked manually.", "Wrong serial sold — warranty activation fails."],
        "fix": "Serial-tracked inventory + POS"}},
    ("retail", "GROCERY"): {1: {"q": "Perishable {unit} — how are expiry, rotation, and shrink managed?",
        "opts": ["FIFO alerts and shrink tracked daily by category.", "Staff rotate when they notice — not systematic.", "Expired product found during audit."],
        "fix": "Fresh category management"}},
    ("retail", "HARDWARE"): {1: {"q": "Customer needs a part for {unit}. How fast can staff locate it?",
        "opts": ["Lookup by project type with aisle/bin in one system.", "Experienced staff know the store.", "Customer waits while three people search."],
        "fix": "Product locator + inventory"}},
    ("retail", "PHARMACY"): {2: {"q": "Prescription {unit} — how is verification and counseling tracked?",
        "opts": ["Dispense workflow with DUR check and counseling logged.", "Pharmacist verifies — counseling when remembered.", "Near-miss caught late — workflow gap."],
        "fix": "Pharmacy workflow system"}},
    ("retail", "FURNITURE"): {3: {"q": "Special-order {unit} — how is delivery and assembly scheduled?",
        "opts": ["Delivery window booked at sale with assembly crew assigned.", "Delivery scheduled after goods arrive — customer waits.", "Customer calls repeatedly for delivery status."],
        "fix": "Special order + delivery scheduling"}},
    ("retail", "JEWELRY"): {2: {"q": "Custom {unit} — how is appraisal, deposit, and production tracked?",
        "opts": ["Order file with spec, deposit, and production milestones.", "Sketch and verbal spec — production by memory.", "Wrong spec fabricated — remake at our cost."],
        "fix": "Custom order tracking"}},
    ("retail", "SPORTING"): {1: {"q": "Seasonal {unit} — how is preseason buy and in-season replenishment managed?",
        "opts": ["Open-to-buy with sell-through triggers reorder.", "Reorder when shelf looks empty.", "Stockout on hot SKU — lost sales all season."],
        "fix": "Open-to-buy + replenishment"}},
    ("retail", "E-COMMERCE"): {3: {"q": "An online order for {unit} — how fast is it fulfilled and tracked?",
        "opts": ["Order-to-ship SLA tracked with tracking auto-sent.", "Picked and shipped — tracking emailed manually.", "Customer opens WISMO ticket before we ship."],
        "fix": "OMS + automated tracking"}},
    ("retail", "AUTO PARTS"): {2: {"q": "Customer needs the right part for {unit}. How is fitment verified?",
        "opts": ["VIN/catalog lookup at POS before picking.", "Counter staff match from experience.", "Wrong part sold — return and lost trust."],
        "fix": "Catalog lookup + fitment verification"}},
    ("retail", "BOOKS/STAT"): {1: {"q": "New {unit} release week — how is stock and display coordinated?",
        "opts": ["Release calendar with allocation and endcap plan.", "Stock arrives — display when staff has time.", "Hot title sold out day one — no reorder trigger."],
        "fix": "Release calendar + allocation"}},
    ("retail", "HOME DECOR"): {3: {"q": "Large {unit} order — how is white-glove delivery coordinated?",
        "opts": ["Delivery window and room-of-choice booked at checkout.", "Delivery team calls customer to schedule.", "Customer frustrated — delivery window missed twice."],
        "fix": "White-glove delivery scheduling"}},
    # EDUCATION
    ("education", "K-12"): {3: {"q": "Mid-{work}, how do parents see progress on {unit}?",
        "opts": ["Parent portal with grades and attendance updated regularly.", "Report cards and occasional emails.", "Parents surprised at conference — no prior visibility."],
        "fix": "Parent portal + progress alerts"}},
    ("education", "HIGHER ED"): {3: {"q": "Mid-{work}, how do advisors track at-risk students in {unit}?",
        "opts": ["Early alert system flags attendance and grade drops.", "Advisors check SIS when students reach out.", "Students leave before intervention happens."],
        "fix": "Early alert + advising workflow"}},
    ("education", "VOCATIONAL"): {2: {"q": "Hands-on {work} — how is competency and hours logged?",
        "opts": ["Skills checklist and hours tracked per accreditation requirement.", "Instructor sign-off on paper logs.", "Graduation delayed — hours documentation incomplete."],
        "fix": "Competency tracking system"}},
    ("education", "ED-TECH"): {2: {"q": "Learners mid-module on {unit} — can you see who is falling behind?",
        "opts": ["LMS analytics flag inactive and low-score learners daily.", "Instructor checks dashboard weekly.", "Dropouts surprise us — no early warning."],
        "fix": "LMS analytics + intervention triggers"}},
    ("education", "CORP TRAINING"): {2: {"q": "Employees in {work} — how is completion and skill transfer tracked?",
        "opts": ["LMS tracks completion, assessment scores, and manager sign-off.", "Completion recorded — skill application not measured.", "Training done — behavior on the job unchanged."],
        "fix": "Training effectiveness tracking"}},
    ("education", "TUTORING"): {3: {"q": "After a block of {work}, how is progress shared with families?",
        "opts": ["Progress report with goals and next steps sent on schedule.", "Verbal update at pickup.", "Family asks what they're paying for — no data."],
        "fix": "Tutoring progress reporting"}},
    ("education", "LANGUAGE"): {1: {"q": "New {client} for {unit} — how is level placement done?",
        "opts": ["Standardized placement test with level assigned before day one.", "Brief conversation to guess level.", "Wrong level — churn within two weeks."],
        "fix": "Placement testing workflow"}},
    ("education", "TEST PREP"): {2: {"q": "Mid-{work}, how are mock scores and weak areas tracked?",
        "opts": ["Mock results feed a personalized study plan automatically.", "Instructor adjusts based on gut feel.", "Score plateau — no data on what's not working."],
        "fix": "Adaptive prep analytics"}},
    ("education", "ARTS & MUSIC"): {3: {"q": "Before {unit} performance, how is rehearsal progress tracked?",
        "opts": ["Rehearsal log with piece readiness rated per student.", "Director knows who's ready — not documented.", "Performance day surprises — pieces not performance-ready."],
        "fix": "Rehearsal tracking + readiness rubric"}},
    ("education", "SPORTS"): {2: {"q": "Athletes in {work} — how are load, attendance, and performance tracked?",
        "opts": ["Training load and performance metrics in one dashboard.", "Coach's notebook and memory.", "Injury from overtraining — load wasn't monitored."],
        "fix": "Athlete performance tracking"}},
    ("education", "EARLY CHILD"): {3: {"q": "Daily {work} — how do families get updates on their child?",
        "opts": ["Daily photo/activity app with milestones logged.", "Verbal handoff at pickup.", "Family feels out of the loop — churn to competitor."],
        "fix": "Family communication app"}},
    ("education", "SPECIAL ED"): {1: {"q": "Before {work}, how is the IEP reviewed and services coordinated?",
        "opts": ["IEP goals mapped to service schedule before term starts.", "Services start — IEP alignment checked mid-year.", "Compliance finding — services didn't match IEP."],
        "fix": "IEP service coordination"}},
    # ENTERTAINMENT
    ("entertainment", "MUSIC"): {3: {"q": "Release day for {unit} — how is distribution and promo coordinated?",
        "opts": ["Release checklist — DSP, PR, and social go live on one timeline.", "Uploaded to DSPs — promo when someone remembers.", "Release underperforms — channels weren't synchronized."],
        "fix": "Release coordination checklist"}},
    ("entertainment", "FILM & VIDEO"): {3: {"q": "Final cut of {unit} ready — how is delivery and approval handled?",
        "opts": ["Review portal with version control and approval timestamps.", "WeTransfer link — feedback in email threads.", "Wrong version delivered to client."],
        "fix": "Review + approval portal"}},
    ("entertainment", "GAMING"): {3: {"q": "Your {unit} build is ready. How is release coordinated across platforms?",
        "opts": ["Platform certification tracker with go/no-go on one board.", "Each platform submitted separately — status in silos.", "Launch delayed — cert failure on one platform."],
        "fix": "Multi-platform release tracker"}},
    ("entertainment", "LIVE EVENTS"): {3: {"q": "Show night for {unit} — how are load-in, run-of-show, and comms managed?",
        "opts": ["Run-of-show app with crew comms and cue callouts.", "Paper run sheet and radio chaos.", "Cue missed — no single source of truth."],
        "fix": "Run-of-show + crew comms"}},
    ("entertainment", "STREAMING"): {3: {"q": "Season of {unit} ready — how is publish and promo scheduled?",
        "opts": ["CMS scheduler with regional rollout and promo synced.", "Episodes uploaded — publish manually.", "Episode leaks early — scheduling error."],
        "fix": "Content scheduling + CMS workflow"}},
    ("entertainment", "SOCIAL MEDIA"): {0: {"q": "Growing audience for {unit} — how is content performance tracked?",
        "opts": ["Analytics dashboard with content pillars and post cadence.", "Post and check likes the next day.", "Growth stalls — no idea which content works."],
        "fix": "Social analytics + content calendar"}},
    ("entertainment", "PUBLISHING"): {3: {"q": "Print/digital release of {unit} — how is distribution coordinated?",
        "opts": ["Pub date checklist — print, digital, and retail sync locked.", "Print ships — digital follows when ready.", "Retail doesn't have stock on pub date."],
        "fix": "Publication coordination checklist"}},
    ("entertainment", "PHOTOGRAPHY"): {3: {"q": "After {work}, how are selects, edits, and client delivery managed?",
        "opts": ["Gallery with proofing, edits, and delivery tracked to deadline.", "Photos edited — gallery link sent when done.", "Client chases delivery — no status visibility."],
        "fix": "Client gallery + delivery workflow"}},
    ("entertainment", "ANIMATION"): {2: {"q": "Production on {unit} — how are shots, versions, and approvals tracked?",
        "opts": ["Shot tracker with version history and director approvals.", "Files in shared drive — latest version unclear.", "Wrong render sent to client."],
        "fix": "Animation production tracker"}},
    ("entertainment", "THEATRE"): {3: {"q": "Opening {unit} — how are cues, cast, and front-of-house coordinated?",
        "opts": ["Call board + cue-to-cue log with FOH checklist.", "Stage manager runs from script and memory.", "Opening night glitch — cue or FOH gap."],
        "fix": "Production call + FOH coordination"}},
    ("entertainment", "SPORTS MEDIA"): {3: {"q": "Broadcast of {unit} — how are feeds, graphics, and ad slots managed?",
        "opts": ["Rundown system with GFX and ad integration live.", "Rundown on paper — GFX lags behind action.", "Wrong graphic on air — rundown out of sync."],
        "fix": "Broadcast rundown system"}},
    ("entertainment", "ADVERTISING"): {2: {"q": "Producing {unit} — how are revisions, assets, and client approvals tracked?",
        "opts": ["Production tracker with revision rounds and approval log.", "Email threads with attachments — version chaos.", "Client approves wrong cut — version mix-up."],
        "fix": "Ad production + approval tracker"}},
}
