"""Conversational Screen 3 flow templates — scenario-based, not quiz-like."""

FLOWS = {
"service": {
  "stages": [
    {"name":"Get Leads","icon":"lead",
     "q":"Someone new reaches out about {unit}. What actually happens next?",
     "opts":["We know where they came from and who's following up.","We talk to them, but nothing gets written down reliably.","Honestly — they just appear. Text, email, referral… nowhere central."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Good conversations happen, but without a record the slow ones go cold — and you can't see what's working.","missing":"When work feels random, every month starts from zero. No warning when the pipeline dries up."},
     "fix":"A simple way to capture every lead"},
    {"name":"Scope","icon":"qualify",
     "q":"Before you quote {unit}, how do you figure out what they actually need?",
     "opts":["We ask the right questions first — then price it.","A quick chat, then we estimate from gut feel.","We start working and figure out scope as we go."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Gut-feel quotes feel fast — until a hard {work} quietly eats your margin.","missing":"Scope creep mid-{work} means you absorb the overrun, not the client."},
     "fix":"A repeatable scoping conversation"},
    {"name":"Proposal","icon":"quote",
     "q":"A keen {client} wants a price on {unit}. How fast do they hear back?",
     "opts":["Same day — we have a template ready to go.","A day or two while someone builds it from scratch.","Whenever we get a quiet moment — could be next week."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"While you're drafting, someone else already replied. Speed quietly loses deals.","missing":"Slow proposals kill momentum before the {work} even starts."},
     "fix":"Proposal templates you can send fast"},
    {"name":"Deliver","icon":"build",
     "q":"You've got more than one {work} on the go. If someone asks 'where are we?' — what do you check?",
     "opts":["One place everyone can look — status is clear.","Mostly messages and one person's memory.","We usually hear something slipped when the {client} calls."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"When status lives in heads and chat threads, deadlines collide without warning.","missing":"Surprises become client escalations — not internal alerts."},
     "fix":"One shared view of active work"},
    {"name":"Get Paid","icon":"invoice",
     "q":"A {work} finished weeks ago. What's going on with getting paid?",
     "opts":["Invoice went out — reminders run without us chasing.","I'll send it soon… when I remember.","Wait — did we actually bill that one?"],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"You become the billing system. Cash comes in late because nothing else chases it.","missing":"Unbilled work and forgotten invoices make cash flow a guessing game."},
     "fix":"Bill when work is done, automatically"},
    {"name":"Retain","icon":"retain",
     "q":"Three months after you {deliver} — what's the relationship with that {client} like?",
     "opts":["Regular check-ins or an ongoing arrangement.","I reach out when they pop into my head.","The {work} ended, so we moved on."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Clients drift to whoever stayed visible — not whoever did the best work.","missing":"Every {work} is a reset. You rebuild trust and pipeline from scratch."},
     "fix":"A simple stay-in-touch rhythm"},
  ]
},
"manufacturing": {
  "stages": [
    {"name":"Demand","icon":"lead",
     "q":"A new order for {unit} lands. What happens in the first hour?",
     "opts":["It's logged with timing and capacity — production knows right away.","It goes on a spreadsheet or email chain — mostly fine.","Someone calls it in — hard to know what's really on the books."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Orders sit in silos — the floor finds out late and plans scramble.","missing":"You over-promise or under-use capacity because nobody sees the full picture."},
     "fix":"One place for every order"},
    {"name":"Plan","icon":"qualify",
     "q":"Before the line runs {unit}, how does the week get planned?",
     "opts":["There's a plan everyone works from — changes are visible.","The supervisor plans each morning from experience.","Whatever feels urgent — no real plan."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Manual planning means changeovers and stockouts you didn't see coming.","missing":"Reactive mode burns overtime and misses delivery dates."},
     "fix":"A production schedule everyone trusts"},
    {"name":"Quality","icon":"quote",
     "q":"Mid-{work}, something's off with quality. What happens?",
     "opts":["We catch it, fix it, and know exactly which batch it was.","We fix it — but the paper trail is thin.","We hear about it from the customer… or an auditor."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Fixes happen, but gaps in records turn small issues into big recalls.","missing":"Late discovery means scrap, returns, and reputation damage."},
     "fix":"Track quality as you go"},
    {"name":"Ship","icon":"build",
     "q":"{unit} is ready to leave the building. How does that handoff feel?",
     "opts":["Pick, pack, ship — everyone knows status.","The warehouse coordinates over radio or chat.","It ships when someone remembers to book the truck."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Coordinating by chat creates mispicks and missed trucks.","missing":"Shipping chaos leads to chargebacks and lost customers."},
     "fix":"Clear fulfillment from floor to dock"},
    {"name":"Invoice","icon":"invoice",
     "q":"Goods went out last week. Has the customer been billed?",
     "opts":["Yes — billing followed shipment automatically.","Finance sends it after they reconcile manually.","Billing happens… whenever someone gets to it."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Manual billing lags shipment — your cash sits waiting.","missing":"Missed or wrong invoices quietly hurt margin."},
     "fix":"Bill when goods ship"},
    {"name":"Account Mgmt","icon":"retain",
     "q":"Six months later — how do you stay close to that buyer?",
     "opts":["Regular check-ins and reorder conversations on schedule.","We talk when they place another order.","No real follow-up — they call when they need more."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Reactive relationships let competitors capture repeat volume.","missing":"Demand feels lumpy because nobody owns the account rhythm."},
     "fix":"Simple account check-in cadence"},
  ]
},
"logistics": {
  "stages": [
    {"name":"Win Load","icon":"lead",
     "q":"A {client} offers {unit}. Walk us through what happens next.",
     "opts":["Quoted, booked, and logged — dispatch knows immediately.","We agree by email, then enter it later.","Accepted on a call — nothing central to look at."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Late entry means dispatch finds out at the last minute — margins shrink.","missing":"Scattered booking creates double-bookings and missed loads."},
     "fix":"Book loads in one place"},
    {"name":"Plan Route","icon":"qualify",
     "q":"Before wheels roll on {unit}, how is the run planned?",
     "opts":["Route and timing planned with room for surprises.","Dispatcher plans from experience.","Driver figures it out on the road."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Manual routing burns fuel and misses time windows.","missing":"Late deliveries and penalty fees stack up."},
     "fix":"Smarter routing before dispatch"},
    {"name":"Track","icon":"build",
     "q":"{unit} is on the move. If the {client} calls — can you answer confidently?",
     "opts":["Yes — we see it live and get alerts when something's off.","When the driver checks in.","We find out when they ask — or when it's late."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Check-call tracking hides delays until they're expensive to fix.","missing":"Blind spots in transit become disputes you can't win."},
     "fix":"Live visibility on every load"},
    {"name":"Deliver","icon":"quote",
     "q":"Delivery day for {unit}. How do you prove it got there?",
     "opts":["Photo, signature, synced right away.","Paper signed — entered into the system later.","Proof goes missing — billing waits on paperwork."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Late proof-of-delivery delays billing and starts arguments.","missing":"Missing proof backs you into write-offs."},
     "fix":"Digital proof at the door"},
    {"name":"Bill","icon":"invoice",
     "q":"Delivery done. When does the invoice go out?",
     "opts":["Automatically — tied to delivery confirmation.","Batch billing once a week.","When someone remembers."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Weekly billing stretches payment cycles and hides missed charges.","missing":"Ad-hoc invoicing leaves money on the table every month."},
     "fix":"Invoice when delivery is confirmed"},
    {"name":"Renew","icon":"retain",
     "q":"After a good run with a {client} — what keeps them coming back?",
     "opts":["Regular reviews — we show up before they shop around.","We react when they send new freight.","No plan — they bid it out every time."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"You become a commodity on every bid without a relationship rhythm.","missing":"Constant re-selling the same lanes burns time and margin."},
     "fix":"Proactive account conversations"},
  ]
},
"agriculture": {
  "stages": [
    {"name":"Market","icon":"lead",
     "q":"A buyer wants {unit}. How do you decide who to sell to and at what price?",
     "opts":["We track buyers and prices — history helps us decide.","Notebook and phone calls — it works most seasons.","Whoever calls on harvest day gets it."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Weak tracking means better prices slip by while you're on the phone.","missing":"Spot-only selling makes margins a rollercoaster."},
     "fix":"Remember your buyers and prices"},
    {"name":"Plan Season","icon":"qualify",
     "q":"Before {work} kicks off — how prepared do you feel?",
     "opts":["Inputs, labor, and timing planned in one view.","Rough plan in a spreadsheet.","Week to week — we figure it out as we go."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Loose planning causes shortages at the worst moment.","missing":"Reactive spending and yield risk compound each season."},
     "fix":"A season plan you can actually follow"},
    {"name":"Operate","icon":"build",
     "q":"Mid-{work}, how do you know things are on track in the field or barn?",
     "opts":["Regular checks and alerts — problems surface early.","We walk the operation and look manually.","Issues show up when damage is already done."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Manual monitoring misses early warnings — yield takes the hit.","missing":"Small fixes become big losses when detection is late."},
     "fix":"Early warning on what matters"},
    {"name":"Sell","icon":"quote",
     "q":"Harvest or sale time for {unit}. How smooth is getting it out the door?",
     "opts":["Grading, packing, pickup — tracked end to end.","Mostly phone calls on pickup day.","Buyers wait while we scramble."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Last-minute coordination discounts your product.","missing":"Chaotic handoffs erode trust with repeat buyers."},
     "fix":"A clear path from field to buyer"},
    {"name":"Collect","icon":"invoice",
     "q":"Product's gone. Has everyone paid what they owe?",
     "opts":["Invoices tied to delivery — reminders run on schedule.","We chase when cash gets tight.","Payments trail delivery by weeks."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Manual collections stretch cash through the off-season.","missing":"Without a system, buyers stretch terms indefinitely."},
     "fix":"Bill and follow up on time"},
    {"name":"Next Season","icon":"retain",
     "q":"Season's over. Do you carry lessons into the next one?",
     "opts":["We review what worked — buyers and inputs planned ahead.","Informal debrief, then move on.","Each season starts fresh — no real review."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Same mistakes repeat when nothing gets written down.","missing":"Margin leaks compound year over year without a learning loop."},
     "fix":"A simple season retrospective"},
  ]
},
"finance": {
  "stages": [
    {"name":"Acquire","icon":"lead",
     "q":"Someone new shows interest in {unit}. What happens in the first few days?",
     "opts":["Logged with a clear next step — nobody falls through.","In an inbox or list — we follow up when we can.","Sits in email until someone has bandwidth."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Good leads go cold quietly without a follow-up rhythm.","missing":"Growth feels random when nobody sees the pipeline."},
     "fix":"Track every new lead"},
    {"name":"Qualify","icon":"qualify",
     "q":"Before you offer {unit}, how do you know they're the right fit?",
     "opts":["Same checklist every time — approvals logged.","Key questions, but it varies by person.","We onboard first and fix gaps later."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Inconsistent checks create rework and compliance headaches.","missing":"Issues surface after you've already invested time."},
     "fix":"A consistent fit-check process"},
    {"name":"Propose","icon":"quote",
     "q":"They're interested and ready to talk numbers on {unit}. How fast do they get an answer?",
     "opts":["Same day — from a template we trust.","Custom deck over several days.","Depends entirely on bandwidth."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Slow answers lose to whoever replied first.","missing":"Inconsistent proposals hurt trust and close rates."},
     "fix":"Proposals you can send quickly"},
    {"name":"Onboard","icon":"build",
     "q":"They said yes. How does getting started feel for them?",
     "opts":["Clear steps — they always know what's next.","Documents back and forth until it's done.","Drags on because nobody tracks the steps."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Document ping-pong delays revenue and frustrates new clients.","missing":"Broken onboarding creates early churn."},
     "fix":"Guided onboarding they can see"},
    {"name":"Serve","icon":"invoice",
     "q":"They're an active {client} on {unit}. When something comes up — how does it get handled?",
     "opts":["Tracked in one place — nothing gets lost.","Handled when they reach out.","We hear about it when they're already upset."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Reactive service misses moments to deepen the relationship.","missing":"Churn shows up too late to save."},
     "fix":"One place for client conversations"},
    {"name":"Retain","icon":"retain",
     "q":"Review time with a long-term {client}. How prepared are you?",
     "opts":["Performance summary and next steps ready to go.","Catch-up when the calendar allows.","No review — they decide quietly whether to stay."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Informal reviews leave relationships open to poaching.","missing":"Silent churn happens when no one owns the relationship."},
     "fix":"Regular review conversations"},
  ]
},
"construction": {
  "stages": [
    {"name":"Find Bid","icon":"lead",
     "q":"A promising {work} comes across your desk. What happens next?",
     "opts":["Tracked with deadlines — we know what to pursue.","Folder and memory — mostly works.","Jobs come through the network — nothing central."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Missed deadlines and wrong pursuits when bids aren't visible.","missing":"Growth feels unpredictable without a bid pipeline."},
     "fix":"See every opportunity in one place"},
    {"name":"Estimate","icon":"qualify",
     "q":"You decide to pursue {unit}. How do you build the number?",
     "opts":["Template and past costs — consistent every time.","Spreadsheet from a similar past job.","Field guess — refined after work starts."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Missed scope gaps kill margin on jobs you thought you'd win.","missing":"Guess-based bids win work you lose money on."},
     "fix":"Estimating you can repeat"},
    {"name":"Contract","icon":"quote",
     "q":"You won {unit}. How fast does paperwork turn into a signed start?",
     "opts":["Contract out within a day — e-sign ready.","Legal review takes a week or more.","Work starts before everything's signed."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Slow contracting delays mobilization and cash flow.","missing":"Starting without signed scope invites disputes."},
     "fix":"Fast contract turnaround"},
    {"name":"Build","icon":"build",
     "q":"On site for {unit} — if the {client} asks for an update, what do you show them?",
     "opts":["Daily log, photos, schedule — one place.","Foreman texts at end of day.","We learn about delays when they call us."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Text updates hide schedule drift until it's costly.","missing":"No job visibility means RFIs and change orders pile up."},
     "fix":"Job progress everyone can see"},
    {"name":"Bill","icon":"invoice",
     "q":"A milestone on {unit} is done. When do you get paid for it?",
     "opts":["Pay app submitted with docs — on schedule.","Invoice when admin catches up.","Billing backlog until cash gets tight."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Late pay apps starve cash and strain GC relationships.","missing":"Billing gaps on {work}s compound into serious cash crises."},
     "fix":"Bill milestones on time"},
    {"name":"Repeat","icon":"retain",
     "q":"You {deliver}. How do you earn the next {unit}?",
     "opts":["Closeout package and a conversation about what's next.","We call if we hear about another project.","No follow-up — hope they call us."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Passive follow-up loses repeat work to proactive competitors.","missing":"Every job is a cold start without a closeout motion."},
     "fix":"Closeout that leads to the next job"},
  ]
},
"retail": {
  "stages": [
    {"name":"Traffic","icon":"lead",
     "q":"You need people walking in (or clicking in). What drives that for you?",
     "opts":["We know what's working — campaigns tied to footfall or clicks.","Promotions when sales dip.","Traffic feels like luck."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Untracked promotions waste spend on the wrong channels.","missing":"Random traffic makes staffing and inventory a guess."},
     "fix":"See what brings people in"},
    {"name":"Merchandise","icon":"qualify",
     "q":"Before someone buys, how confident are you about what's on the shelf?",
     "opts":["Stock levels clear — reorders trigger before empty shelves.","Counts done periodically — mostly fine.","Customers tell us when we're out."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Periodic counts miss stockouts and shrink between audits.","missing":"Blind inventory means lost sales and frustrated customers."},
     "fix":"Inventory that warns you early"},
    {"name":"Sell","icon":"quote",
     "q":"Someone's ready to buy. How does checkout feel — for them and for you?",
     "opts":["Fast — one system, online or in-store.","Works, but promos and discounts are manual.","Lines build because things don't connect."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Manual steps slow peak hours and lose baskets.","missing":"Friction at checkout kills the sale you worked to get."},
     "fix":"Checkout that doesn't get in the way"},
    {"name":"Fulfill","icon":"build",
     "q":"Order placed. What happens before it reaches the {client}?",
     "opts":["Pick, pack, ship — they get updates along the way.","We fulfill it, but updates are manual.","They call asking where it is."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Manual updates drive 'where's my order?' calls and bad reviews.","missing":"Opaque fulfillment kills repeat purchases."},
     "fix":"Fulfillment with automatic updates"},
    {"name":"Reconcile","icon":"invoice",
     "q":"End of the week — do sales, payments, and the bank all agree?",
     "opts":["Daily close — everything matched.","Reconciled when accounting has time.","Discrepancies show up at month-end."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Delayed reconciliation hides leakage until it's large.","missing":"Operating blind to shrink and errors."},
     "fix":"A daily close you can trust"},
    {"name":"Loyalty","icon":"retain",
     "q":"They bought once. What brings that {client} back?",
     "opts":["Personal follow-ups — we remember what they like.","Occasional email blasts.","We hope they return on their own."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Generic blasts underperform a personal touch by a wide margin.","missing":"Without a retention loop, you re-buy every customer from scratch."},
     "fix":"Stay in touch after the sale"},
  ]
},
"education": {
  "stages": [
    {"name":"Enroll","icon":"lead",
     "q":"A {client} wants in on {unit}. What's the experience like getting started?",
     "opts":["Clear steps — they always know what's next.","Forms emailed back and forth.","Phone tag until someone gives up."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Manual enrollment leaks people between inquiry and start date.","missing":"Phone-tag caps growth and frustrates families."},
     "fix":"Enrollment that doesn't lose people"},
    {"name":"Assess","icon":"qualify",
     "q":"Before teaching {unit}, how do you place the {client} at the right level?",
     "opts":["Standard check — logged so everyone agrees.","Informal chat about where they are.","Everyone starts at the same point."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Wrong placement causes churn when content doesn't fit.","missing":"Poor outcomes lead to refunds and bad word of mouth."},
     "fix":"A quick placement conversation"},
    {"name":"Teach","icon":"build",
     "q":"Mid-{work}, can you tell who's thriving and who needs help?",
     "opts":["Yes — attendance and progress visible to the team.","The instructor knows — mostly in their head.","We find out when someone complains."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Instructor-only tracking hides at-risk learners until too late.","missing":"Dropouts and bad reviews follow invisible struggles."},
     "fix":"See progress as it happens"},
    {"name":"Report","icon":"quote",
     "q":"Halfway through {work}, do families or stakeholders know how it's going?",
     "opts":["Updates go out on schedule — no one has to ask.","Reports built manually before meetings.","They ask because they haven't heard anything."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Manual reporting eats instructor time and still arrives late.","missing":"Silence erodes trust fast."},
     "fix":"Progress updates that send themselves"},
    {"name":"Bill","icon":"invoice",
     "q":"Fees for {unit} — how does getting paid feel?",
     "opts":["Recurring billing with reminders — predictable.","Invoices when someone remembers.","Awkward, inconsistent follow-up."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Inconsistent billing creates awkward conversations and arrears.","missing":"Weak collection threatens cash and continuation."},
     "fix":"Tuition billing on autopilot"},
    {"name":"Retain","icon":"retain",
     "q":"Term's ending. What brings that {client} back next time?",
     "opts":["Renewal conversation ready — next step clear.","We mention re-enrollment at pickup.","They drift unless they proactively return."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Casual mentions miss a big chunk of repeat enrollments.","missing":"Every term becomes a rebuild without a renewal rhythm."},
     "fix":"A simple re-enrollment path"},
  ]
},
"entertainment": {
  "stages": [
    {"name":"Audience","icon":"lead",
     "q":"You need eyeballs for {unit}. How do you grow reach?",
     "opts":["We know what's working — content on a rhythm.","Post when something's ready.","Reach feels unpredictable."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Inconsistent publishing wastes momentum between releases.","missing":"Every launch starts from zero when reach is random."},
     "fix":"A content rhythm you can sustain"},
    {"name":"Pitch","icon":"qualify",
     "q":"A partner wants {unit}. How do you win them over?",
     "opts":["Pitch and scope from templates — fast and clear.","Custom pitch every time from scratch.","Verbal agreement — details later."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Custom pitches slow deals and blur scope.","missing":"Verbal-only deals lead to payment and delivery fights."},
     "fix":"A pitch kit you can reuse"},
    {"name":"Produce","icon":"build",
     "q":"Production on {unit} is underway. How organized does it feel?",
     "opts":["Tasks, assets, deadlines — one tracker.","Shared drive and group chat.","Deadlines slip until someone panics."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Chat-based production loses versions and misses handoffs.","missing":"Last-minute fire drills eat budget and morale."},
     "fix":"Production tracking that keeps up"},
    {"name":"Release","icon":"quote",
     "q":"{unit} is ready to go live. How coordinated is launch day?",
     "opts":["Checklist across platforms — one timeline.","Posted manually, platform by platform.","Goes live whenever it's 'good enough'."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Manual release creates inconsistent rollouts and missed windows.","missing":"Unplanned launches waste the production investment."},
     "fix":"A release checklist everyone follows"},
    {"name":"Monetize","icon":"invoice",
     "q":"After release — do you know if {unit} actually made money?",
     "opts":["Yes — revenue tied to each release.","Spreadsheet updated monthly.","Not sure which projects paid off."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Delayed tracking hides what's working until too late.","missing":"You repeat unprofitable projects without knowing."},
     "fix":"See revenue per release"},
    {"name":"Retain Fans","icon":"retain",
     "q":"After {unit} drops — what keeps the audience warm?",
     "opts":["Post-release plan with regular touchpoints.","A few follow-up posts if there's time.","Silence until the next project."],
     "states":["solid","shaky","missing"],
     "diag":{"shaky":"Sparse follow-up lets heat fade before the next launch.","missing":"Long gaps reset audience growth."},
     "fix":"Stay visible between releases"},
  ]
},
}
