"""Conversational stage-question hooks — scenario-based, not quiz-like."""

# Stage index → question override only (options/diag come from category template)
OVERRIDES = {
    # SERVICE
    ("service", "IT & TECH"): {0: {"q": "A new prospect lands on your site today. What happens in the next hour?"}},
    ("service", "CONSULTING"): {1: {"q": "A CEO says \"we need help with {unit}.\" What do you do before talking fees?"}},
    ("service", "LEGAL"): {1: {"q": "Someone describes {unit} on a call. What happens before you quote a fee?"}},
    ("service", "ACCOUNTING"): {4: {"q": "Month-end for {unit}, has everyone been billed for the work you actually did?"}},
    ("service", "MARKETING"): {0: {"q": "A brand reaches out about {unit}. What's the first conversation like?"}},
    ("service", "HEALTHCARE"): {0: {"q": "A new {client} needs {unit}. Walk in the door, what happens first?"}},
    ("service", "STAFFING"): {0: {"q": "A {client} says \"we need to fill {unit}.\" How fast do you get moving?"}},
    ("service", "CLEANING"): {3: {"q": "Multiple sites tonight. How do you know each one actually got done?"}},
    ("service", "SECURITY"): {3: {"q": "Something happens on {work}. How does your team handle it?"}},
    ("service", "HOSPITALITY"): {0: {"q": "A {client} wants {unit}. What does booking feel like for them?"}},
    ("service", "FOOD SERVICE"): {2: {"q": "Big {unit} tomorrow. When do you feel ready, and when do you panic?"}},
    ("service", "CREATIVE"): {2: {"q": "The {client} loves the direction on {unit}. What happens before work starts?"}},
    # MANUFACTURING
    ("manufacturing", "FOOD & BEV"): {2: {"q": "Something's off on the line during {unit}. How do you catch it?"}},
    ("manufacturing", "ELECTRONICS"): {2: {"q": "Mid-{work}, a batch looks wrong. What happens next?"}},
    ("manufacturing", "TEXTILES"): {1: {"q": "A rush order for {unit}. How do you slot it into the week?"}},
    ("manufacturing", "CHEMICALS"): {2: {"q": "Mid-{work}, something deviates from spec. Who finds out first?"}},
    ("manufacturing", "METAL & STEEL"): {1: {"q": "A hot {unit} hits the floor. How do you decide what runs first?"}},
    ("manufacturing", "AUTOMOTIVE"): {2: {"q": "The customer flags a quality issue on {unit}. Can you trace it back?"}},
    ("manufacturing", "FURNITURE"): {3: {"q": "{unit} is boxed and ready. How confident are you it ships today?"}},
    ("manufacturing", "MEDICAL"): {2: {"q": "Before {unit} leaves the building, are you confident in the paperwork?"}},
    ("manufacturing", "CONSTRUCTION"): {1: {"q": "The site needs {unit} by Friday. How do you plan production?"}},
    ("manufacturing", "PLASTICS"): {2: {"q": "Parts start drifting out of spec mid-{work}. When do you notice?"}},
    ("manufacturing", "PRINT & PAPER"): {2: {"q": "Color looks wrong mid-{work}. How do you catch it before it ships?"}},
    ("manufacturing", "AGRI-PROC"): {2: {"q": "Processing {unit}, can you trace it back to the source lot?"}},
    # AGRICULTURE
    ("agriculture", "CROP FARMING"): {2: {"q": "Mid-{work}, the crop looks stressed. How soon do you know?"}},
    ("agriculture", "LIVESTOCK"): {2: {"q": "Mid-{work}, an animal health issue starts. How do you spot it?"}},
    ("agriculture", "DAIRY"): {2: {"q": "At {work} time, how do you know the milk is good before the truck leaves?"}},
    ("agriculture", "POULTRY"): {2: {"q": "Mid-{work}, mortality ticks up. How early do you see it?"}},
    ("agriculture", "AQUACULTURE"): {2: {"q": "The water on {unit} doesn't look right. How do you find out?"}},
    ("agriculture", "HORTICULTURE"): {2: {"q": "Greenhouse {unit}, who notices when climate slips out of range?"}},
    ("agriculture", "ORGANIC"): {1: {"q": "Planning {work}, could you show an auditor your input records tomorrow?"}},
    ("agriculture", "PROCESSING"): {2: {"q": "If there was a recall on {unit}, how fast could you trace it?"}},
    ("agriculture", "PLANTATION"): {3: {"q": "Harvest day for {unit}. Does field-to-factory feel calm or chaotic?"}},
    ("agriculture", "SEED SUPPLY"): {0: {"q": "A {client} orders {unit}. Wrong variety shipped, how likely is that?"}},
    ("agriculture", "IRRIGATION"): {3: {"q": "You finish {unit}. How does the farmer know it actually works?"}},
    ("agriculture", "EXPORT/TRADE"): {3: {"q": "Exporting {unit}, when do paperwork headaches usually appear?"}},
    # LOGISTICS
    ("logistics", "ROAD/TRUCKING"): {1: {"q": "Dispatching {unit}, how do you pick the driver and route?"}},
    ("logistics", "AIR FREIGHT"): {1: {"q": "Urgent {unit}. How do you make the flight cutoff?"}},
    ("logistics", "SEA/OCEAN"): {1: {"q": "Booking {unit}, how do you avoid a rolled container?"}},
    ("logistics", "RAIL"): {2: {"q": "{unit} is on the rails. If the {client} calls, what can you tell them?"}},
    ("logistics", "WAREHOUSING"): {3: {"q": "Pick wave for {unit}. How do you know the right stuff left the building?"}},
    ("logistics", "LAST MILE"): {1: {"q": "Same-day {unit}. How do drivers know where to go next?"}},
    ("logistics", "COLD CHAIN"): {2: {"q": "That load needs to stay cold. If the temperature slips, how soon do you know?"}},
    ("logistics", "CUSTOMS"): {0: {"q": "An importer sends docs for {unit}. What happens before you file?"}},
    ("logistics", "SUPPLY CHAIN"): {1: {"q": "Planning {unit}, do you feel ahead of stockouts or always reacting?"}},
    ("logistics", "MOVING"): {2: {"q": "Mid-{work}, a box goes missing. When do you find out?"}},
    ("logistics", "E-COMM FULFIL"): {3: {"q": "Same-day {unit}. Do you know by noon if you'll hit the cut-off?"}},
    ("logistics", "FREIGHT FWDG"): {1: {"q": "Door-to-door {unit} across modes. One person know the full picture?"}},
    # FINANCE
    ("finance", "BANKING"): {1: {"q": "Someone wants {unit}. What does getting approved feel like for them?"}},
    ("finance", "INSURANCE"): {4: {"q": "A claim comes in on {unit}. What's the customer's experience?"}},
    ("finance", "INVESTMENT"): {3: {"q": "The {client} says yes to {unit}. How fast is their money actually working?"}},
    ("finance", "ACCOUNTING"): {4: {"q": "The {unit} work is done. Has the client been billed yet?"}},
    ("finance", "FINTECH"): {2: {"q": "Someone finishes sign-up for {unit}. How long until they're actually in?"}},
    ("finance", "LENDING"): {1: {"q": "A {client} applies for {unit}. How does the yes/no decision happen?"}},
    ("finance", "WEALTH MGMT"): {5: {"q": "Annual review with a {client}. Could you walk in prepared tomorrow?"}},
    ("finance", "PAYMENTS"): {3: {"q": "A merchant goes live on {unit}. How do you know it's actually working?"}},
    ("finance", "CRYPTO"): {1: {"q": "Someone signs up for {unit}. What does verification feel like on their end?"}},
    ("finance", "RISK"): {1: {"q": "Starting {unit}. How painful is getting the data you need?"}},
    ("finance", "TRADING"): {3: {"q": "A {client} wants {unit} executed. Can you show them what happened after?"}},
    ("finance", "MICROFINANCE"): {4: {"q": "End of {work}. Does everyone know who paid and who didn't?"}},
    # CONSTRUCTION
    ("construction", "RESIDENTIAL"): {3: {"q": "On the {work} site, if the {client} asks for an update, what do you show?"}},
    ("construction", "COMMERCIAL"): {3: {"q": "Commercial {work}. When an RFI sits too long, how do you find out?"}},
    ("construction", "INFRASTRUCTURE"): {3: {"q": "Public {work}. If an inspector shows up, are the logs ready?"}},
    ("construction", "ELECTRICAL"): {3: {"q": "Before you cover the walls on {work}, can you prove the rough-in passed?"}},
    ("construction", "PLUMBING"): {3: {"q": "Pressure test on {work}. Would you bet the drywall on your records?"}},
    ("construction", "INTERIOR"): {2: {"q": "The {client} signed off on {unit}. How fast does work actually start?"}},
    ("construction", "RENOVATION"): {1: {"q": "Renovating {unit} while people still live there. What surprises you mid-job?"}},
    ("construction", "DEMOLITION"): {1: {"q": "Before {work} starts, permits and hazmat sorted, or figured out later?"}},
    ("construction", "REAL ESTATE"): {0: {"q": "A new {unit} crosses your desk. How do you decide to pursue it?"}},
    ("construction", "CIVIL ENG"): {2: {"q": "Designing {unit}. How do you know the contractor has the right drawing?"}},
    ("construction", "ENVIRONMENTAL"): {3: {"q": "Remediation {work}. If the regulator calls, how fast can you answer?"}},
    ("construction", "FUEL/ENERGY"): {1: {"q": "A fuel/energy site job. Do compliance costs surprise you mid-project?"}},
    # RETAIL
    ("retail", "APPAREL"): {1: {"q": "New season arriving. Do the right sizes hit the floor on day one?"}},
    ("retail", "ELECTRONICS"): {1: {"q": "High-value item sold. Are you confident the serial and warranty match?"}},
    ("retail", "GROCERY"): {1: {"q": "Perishables on shelf. Who catches expiry before the customer does?"}},
    ("retail", "HARDWARE"): {1: {"q": "Customer needs something for a project. How long do they wait while you search?"}},
    ("retail", "PHARMACY"): {2: {"q": "Prescription ready. Does the {client} leave knowing how to take it safely?"}},
    ("retail", "FURNITURE"): {3: {"q": "Special order sold. Does the {client} know when it's coming before they ask?"}},
    ("retail", "JEWELRY"): {2: {"q": "Custom piece ordered. Could you recreate the spec if the jeweler left tomorrow?"}},
    ("retail", "SPORTING"): {1: {"q": "Hot item selling fast. Do you reorder before the shelf goes bare?"}},
    ("retail", "E-COMMERCE"): {3: {"q": "Online order in. Does the {client} get tracking before they email you?"}},
    ("retail", "AUTO PARTS"): {2: {"q": "Customer needs a part. How sure are you it's the right fit before they leave?"}},
    ("retail", "BOOKS/STAT"): {1: {"q": "Big release week. Sold out on day one, did you see it coming?"}},
    ("retail", "HOME DECOR"): {3: {"q": "Large delivery sold. Does the {client} know the window before they chase you?"}},
    # EDUCATION
    ("education", "K-12"): {3: {"q": "Mid-{work}, do parents know how their child is doing, or are they guessing?"}},
    ("education", "HIGHER ED"): {3: {"q": "Mid-{work}, do you spot struggling students before they drop out?"}},
    ("education", "VOCATIONAL"): {2: {"q": "Hands-on {work}. Could you prove hours and skills if audited tomorrow?"}},
    ("education", "ED-TECH"): {2: {"q": "Learners mid-module. Do you know who's falling behind this week?"}},
    ("education", "CORP TRAINING"): {2: {"q": "Training done. Do people actually change how they work, or just check a box?"}},
    ("education", "TUTORING"): {3: {"q": "After a month of {work}, can the family see progress, or just hope?"}},
    ("education", "LANGUAGE"): {1: {"q": "New {client} walks in. How do you know they're in the right level?"}},
    ("education", "TEST PREP"): {2: {"q": "Mid-{work}, mock scores flat. Do you know what's not working?"}},
    ("education", "ARTS & MUSIC"): {3: {"q": "Performance approaching. Are you confident everyone's ready, or crossing fingers?"}},
    ("education", "SPORTS"): {2: {"q": "Mid-{work}, is anyone being pushed too hard, or slipping through?"}},
    ("education", "EARLY CHILD"): {3: {"q": "Pick-up time. Do families feel connected to what happened today?"}},
    ("education", "SPECIAL ED"): {1: {"q": "Before {work} starts, does the plan match what services actually happen?"}},
    # ENTERTAINMENT
    ("entertainment", "MUSIC"): {3: {"q": "Release day. Do all the channels go live together, or trickle out?"}},
    ("entertainment", "FILM & VIDEO"): {3: {"q": "Final cut ready. How do you know the {client} approved the right version?"}},
    ("entertainment", "GAMING"): {3: {"q": "Build ready to ship. One platform fails cert, how do you find out?"}},
    ("entertainment", "LIVE EVENTS"): {3: {"q": "Show night. One source of truth for cues, or chaos on headsets?"}},
    ("entertainment", "STREAMING"): {3: {"q": "Season ready to drop. Could the wrong episode go live by mistake?"}},
    ("entertainment", "SOCIAL MEDIA"): {0: {"q": "Growing an audience. Do you know what content actually works, or guess?"}},
    ("entertainment", "PUBLISHING"): {3: {"q": "Pub date. Is the book actually in stores when readers expect it?"}},
    ("entertainment", "PHOTOGRAPHY"): {3: {"q": "After the {work}. Does the {client} know when photos arrive, or keep asking?"}},
    ("entertainment", "ANIMATION"): {2: {"q": "Mid-production. Could you hand off to another artist without losing the thread?"}},
    ("entertainment", "THEATRE"): {3: {"q": "Opening night. If a cue gets missed, how does the team recover?"}},
    ("entertainment", "SPORTS MEDIA"): {3: {"q": "Going live. Graphics and action in sync, or chasing the play?"}},
    ("entertainment", "ADVERTISING"): {2: {"q": "Client wants changes on {unit}. How do you avoid sending the wrong cut?"}},
}
